Repository NervJS/taro, pull requests merged in 2019-11, with the labels that each got.

#4727 feat(taro-cli): 增加UI模块快应用转换index入口
  packages/taro-cli/src/ui/common.ts
  packages/taro-cli/src/ui/index.ts
Labels: 快应用

#4734 feat(taro-cli): 增加UI模块快应用文件修改监控
  packages/taro-cli/src/ui/index.ts
Labels: 快应用

#4849 feat:(rn) rn 环境下CoverView 与 CoverImage 支持向下兼容为 View 与Image
  packages/taro-components-rn/src/index.ts
Labels: React Native

#4866 feat: rn 配置添加onlyTaroToRn字段,支持项目构建只编译不打包
  packages/taro-cli/src/rn.ts
Labels: React Native

#4843 feat(cli):给config的copy加上watch选项,使之可以监听并复制
  packages/taro-cli/src/util/index.ts
  packages/taro-cli/src/util/types.ts
Labels: CLI

#4924 fix(taro-cli): 小程序组件打包时，将打包参数传递到依赖文件的打包中
  packages/taro-cli/src/mini/component.ts
Labels: CLI

#4847 fix(taro-cli)：增加taro-cli及运行时框架，版本不一致判断及提示
  docs/GETTING-STARTED.md
  packages/taro-cli/src/build.ts
  packages/taro-cli/src/util/constants.ts
  packages/taro-cli/src/util/index.ts
Labels: CLI

#4802 fix: 修正previewImage点透问题
  packages/taro-h5/src/api/image/react-wx-images-viewer/components/ImageContainer.js
Labels: H5

#4780 Bug css url loader
  packages/taro-cli/src/mini/compileStyle.ts
Labels: bug

#4722 feat(webpack-runner): h5环境支持自定义source-map格式
  docs/config-detail.md
  packages/taro-webpack-runner/src/config/dev.conf.ts
  packages/taro-webpack-runner/src/config/prod.conf.ts
  packages/taro-webpack-runner/src/util/chain.ts
  packages/taro-webpack-runner/src/util/types.ts
Labels: H5

#4850 feat: 在rn环境下,app.js config 下的 window属性支持配置backgroundColor
  docs/tutorial.md
  packages/taro-router-rn/src/initRouter.js
  packages/taro-router-rn/src/utils.js
Labels: React Native

#4663 fix(alipay): 函数 Page 组件没有触发effect cleanup
  packages/taro-alipay/src/create-component.js
Labels: 支付宝小程序

#4947 Update hooks.md
  docs/hooks.md
Labels: docs, 文档
