Repository NervJS/taro, pull requests merged in 2019-12, with the labels that each got.

#4993 fix(taro-qq): fix error in create-component.js
  packages/taro-qq/src/create-component.js
Labels: QQ 轻应用

#5006 Fixrn
  packages/taro-cli/src/rn.ts
  packages/taro-transformer-wx/src/options.ts
Labels: React Native

#4799 docs: Video视频组件文档更新
  docs/components/media/video.md
Labels: docs

#5135 componentWillUnmount lifecycle
  packages/taro-components/src/components/image/index.js
  packages/taro-components/src/components/input/index.js
Labels: H5

#5108 fix(RN): 修复 previewImage 加载中的 loading 提示
  packages/taro-rn/src/api/image/previewImage.tsx
Labels: React Native

#5181 fix(transform): 修复微信开发者工具key警告(使用常量key判断)
  packages/taro-transformer-wx/src/create-html-element.ts
Labels: 编译器

#5092 fix(taro-h5): fix scroll issue in iOS when using showToast/showModal/showActionSheet
  packages/taro-h5/src/api/interactive/actionSheet.js
  packages/taro-h5/src/api/interactive/modal.js
  packages/taro-h5/src/api/interactive/toast.js
  packages/taro-h5/src/api/utils/index.js
Labels: H5

#5107 fix: h5环境previewImage左右滑动时触发浏览器前进、后退
  packages/taro-h5/src/api/image/react-wx-images-viewer/components/ImageContainer.js
  packages/taro-h5/src/api/image/react-wx-images-viewer/components/WxImageViewer.css
Labels: H5
