Repository NervJS/taro, pull requests merged in 2020-09, with the labels that each got.

#7473 fix(components): 修复 H5 虚拟列表滚动后不能点击的问题，fix #7140
  packages/taro-components/virtual-list/react/createListComponent.js
  packages/taro-runtime/src/dom/style_properties.ts
Labels: V-3

#7462 RouterInfo add shareTicket scene from app.tsx
  packages/taro/types/taro.component.d.ts
Labels: V-3

#7492 fix(runner-utils): 修复 require.context 问题，fix #6920
  packages/taro-runner-utils/package.json
  packages/taro-runner-utils/src/resolve/MultiPlatformPlugin.ts
Labels: V-3

#7450 fix(runner): 修复样式条件编译问题，close #7410
  packages/taro-mini-runner/src/webpack/chain.ts
  packages/taro-webpack-runner/__tests__/__snapshots__/vue.spec.ts.snap
  packages/taro-webpack-runner/src/util/chain.ts
Labels: V-3

#7488 fix(webpack-runner): 修复 WDS 设置 host 的问题，fix #7291
  packages/taro-webpack-runner/src/index.ts
Labels: V-3

#7465 fix(convert): 修复 taro convert 后 react 项目报错的问题
  packages/taro-cli/src/rn/transformJS.ts
  packages/taro-cli/yarn.lock
  packages/taro-helper/yarn.lock
  packages/taro-mini-runner/__tests__/__snapshots__/css-modules.spec.ts.snap
  packages/taro-mini-runner/yarn.lock
  packages/taro-service/yarn.lock
  packages/taro-webpack-runner/yarn.lock
  packages/taro-with-weapp/package.json
  packages/taro-with-weapp/src/clone.js
  packages/taro-with-weapp/src/diff.js
  packages/taro-with-weapp/src/index.ts
  packages/taro-with-weapp/src/utils.ts
Labels: V-3

#7503 fix(mini-runner): 修复UI库link到本地使用时Current值错误的问题
  packages/taro-mini-runner/src/webpack/base.conf.ts
Labels: V-3

#7518 fix(taro): 完善pxTransform的d.ts，增加第二个参数designWidth
  packages/taro/types/taro.extend.d.ts
Labels: V-3

#7506 fix: 完善ref类型推导
  packages/taro-components/types/common.d.ts
Labels: V-2

#7549 fix(components): 更新 swiper 的修复
  packages/taro-components/__tests__/swiper.spec.js
  packages/taro-components/src/components.d.ts
  packages/taro-components/src/components/swiper/swiper.tsx
  packages/taro-components/types/components.d.ts
Labels: V-3

#7535 fix(components): 修复swiper和movableview的interface拼写错误
  packages/taro-components/types/MovableView.d.ts
  packages/taro-components/types/Swiper.d.ts
Labels: V-3

#7557 fix(components): 更新 input 的修复
  packages/taro-components/src/components/input/input.tsx
Labels: V-3

#7560 refactor(taro/type): 修改Taro.eventCenter的类型推导
  packages/taro/types/taro.extend.d.ts
Labels: V-3

#7572 fix(shared): 组件 LivePlayer 可以渲染子元素，fix #7552
  packages/shared/src/template.ts
Labels: V-3

#7613 fix(mini-runner): 修复 baseLevel 配置不生效的问题
  packages/taro-mini-runner/src/plugins/MiniPlugin.ts
Labels: V-3

#7640 修复路由默认渲染模式与文档描述不同问题
  packages/taro-router/src/history.ts
Labels: V-3

#7612 types: Ad add adType and adTheme
  packages/taro-components/types/Ad.d.ts
Labels: V-3

#7611 types: add onThemeChange and offThemeChange
  packages/taro/types/api/base/weapp/app-event.d.ts
Labels: V-3

#7696 fix(h5): api upload abort fix #7448
  packages/taro-h5/src/api/fileTransfer/uploadFile.js
Labels: A-api, T-h5, V-2

#7522 fix(h5): uncompiled es syntax
  package.json
  packages/taro-cli/__tests__/info.spec.ts
  packages/taro-cli/__tests__/update.spec.ts
  packages/taro-components/package.json
  packages/taro-components/yarn.lock
  packages/taro-h5/package.json
  packages/taro-h5/src/api/request/index.js
  packages/taro-h5/yarn.lock
  packages/taro-loader/src/h5.ts
  packages/taro-router-rn/package.json
  packages/taro-webpack-runner/__tests__/__snapshots__/babel.spec.ts.snap
  packages/taro-webpack-runner/__tests__/__snapshots__/config.spec.ts.snap
  packages/taro-webpack-runner/__tests__/__snapshots__/css-modules.spec.ts.snap
  packages/taro-webpack-runner/__tests__/__snapshots__/nerv.spec.ts.snap
  packages/taro-webpack-runner/__tests__/__snapshots__/react.spec.ts.snap
  packages/taro-webpack-runner/__tests__/__snapshots__/sass.spec.ts.snap
  packages/taro-webpack-runner/__tests__/__snapshots__/subpackages.spec.ts.snap
  packages/taro-webpack-runner/__tests__/__snapshots__/ts.spec.ts.snap
  packages/taro-webpack-runner/__tests__/__snapshots__/vue.spec.ts.snap
  packages/taro-webpack-runner/__tests__/__snapshots__/vue3.spec.ts.snap
  yarn.lock
Labels: V-3

#7590 fix(alipay):支付宝小程序在showModal属性showCancel且没有cancelText真机调试按钮显示undefined
  packages/taro/apis/alipay.js
Labels: V-3

#7623 增加微信小程序 Swiper 的 snap-to-edge 属性
  packages/shared/src/components.ts
  packages/taro-components/types/Swiper.d.ts
Labels: V-3

#7697 fix(h5): api upload abort fix #7448
  packages/taro-h5/src/api/fileTransfer/uploadFile.js
Labels: A-api, T-h5, V-3

#7695 fix(h5): upload location api to fix #7453
  packages/taro-h5/src/api/index.js
  packages/taro-h5/src/api/location/chooseLocation.js
  packages/taro-h5/src/api/location/style.css
Labels: A-api, T-h5, V-3

#7701 Add missing map callout's anchorX and anchorY
  packages/taro-components/types/Map.d.ts
Labels: A-typings, V-3

#7685 chore: modify showActionSheet callback success res type
  packages/taro/types/api/ui/interaction.d.ts
Labels: A-typings, V-3

#7679 fix(type): Add the missed parameter to useRouter
  packages/taro/types/taro.hooks.d.ts
Labels: A-typings, V-3
