Repository NervJS/taro, pull requests merged in 2020-07, with the labels that each got.

#7139 fix(loader): 修复 h5 下 vue 在生产环境不工作的问题, fix #7129
  packages/taro-loader/src/utils.ts
  packages/taro-webpack-runner/__tests__/__snapshots__/vue.spec.ts.snap
Labels: V-3

#7101 fix(shared): 给 Map 组件的 setting 添加默认值, fix #6949
  packages/shared/src/components.ts
Labels: V-3

#7141 fix(taro-runtime): <sub> should be an inline element
  packages/taro-runtime/src/dom/html/tags.ts
Labels: V-3

#7167 fix(H5):webpack devServer open the browser with wrong Host
  packages/taro-webpack-runner/src/config/devServer.conf.ts
Labels: V-3

#7162 fix(h5): 修复不支持fetch的浏览器调用request无法返回结果
  packages/taro-h5/src/api/request/index.js
Labels: V-3

#7095 fix(components): 修正虚拟列表 VirtualList 滚动时抖动的问题
  packages/taro-components/virtual-list/react/createListComponent.js
Labels: V-3

#7189 fix(runtime): 给每个页面的 key 增加一个独立 id，避免 key 重复而报错
  packages/taro-runtime/src/dsl/react.ts
Labels: V-3

#7100 fix(rn): common js 样式路径错误的问题
  packages/taro-rn-runner/package.json
  packages/taro-rn-runner/src/loaders/JSXToStylesSheetLoader.ts
  packages/taro-rn-runner/src/plugins/RNPlugin.ts
  packages/taro-rn-runner/src/utils/debug.ts
  packages/taro-rn-runner/src/webpack/chain.ts
  packages/taro-rn-runner/yarn.lock
Labels: T-rn, V-2

#6072 fix(component-rn): RadioGroup组件Radio设置checked 不生效
  packages/taro-components-rn/src/components/Radio/radioGroup.tsx
Labels: T-rn, V-2

#5967 fix: fix the picker in android webview of low version
  packages/taro-components/src/components/picker/index.js
Labels: A-components, V-2

#6059 fix(taro-h5): 修复pageScrollTo方法滚动的实际位置与给定的目标位置不符
  packages/taro-h5/src/api/scroll/index.js
Labels: A-api, V-2
