Repository NervJS/taro, pull requests merged in 2020-01, with the labels that each got.

#5227 windows下配置weapp.compile.exclude 为npm包时路径问题 #4775
  packages/taro-cli/src/util/resolve_npm_files.ts
Labels: CLI

#5248 fix(weapp): allow Taro.getUserInfo to take no param
  packages/taro/types/api/open-api/user-info.d.ts
Labels: typings

#5250 fix(weapp): incorrect Taro.canvasToTempFilePath typing
  packages/taro/types/api/canvas/index.d.ts
Labels: typings

#5257 fix(taro-alipay): 兼容支付宝和微信 request 回调函数
  packages/taro-alipay/src/native-api.js
Labels: 支付宝小程序

#5270 fix(weapp): 修复 Taro.cloud 部分函数返回错误的类型定义
  packages/taro/types/api/cloud/index.d.ts
Labels: typings

#5269 chore(taro-swan): requestPolymerPayment赋值给requestPayment方法
  packages/taro-swan/src/native-api.js
Labels: 百度小程序

#5273 fix: 添加微信小程序webp属性
  packages/taro-components/types/Image.d.ts
  packages/taro/types/taro.component.d.ts
Labels: typings

#5284 补全环境变量文档
  docs/apis/about/env.md
  website/versioned_docs/version-1.3.14/apis/about/env.md
Labels: docs

#5355 fix(cli, mini-runner): 修复小程序 watch 时支持压缩的问题 close #5322
  packages/taro-cli/src/mini/index.ts
  packages/taro-mini-runner/src/index.ts
  packages/taro-mini-runner/src/utils/types.ts
Labels: CLI
