Repository NervJS/taro, pull requests merged in 2020-12, with the labels that each got.

#7745 feat: 让微信小程序可以自定义project.config.json文件的源文件名
  packages/taro-cli/src/presets/platforms/weapp.ts
Labels: V-3

#8173 fix(taro): 编译缺少 framework 字段时报错，fix #8092
  packages/taro-service/src/Kernel.ts
Labels: V-3

#8178 Fix/components
  packages/shared/src/components.ts
  packages/shared/src/template.ts
  packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/jd.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap
Labels: V-3

#8192 fix(taro-h5): 补全 taro-h5 导出的散装 API, fix #8189
  packages/taro-h5/src/api/customComponent/index.js
  packages/taro-h5/src/api/index.js
  packages/taro-h5/src/taro/index.js
Labels: V-3

#8050 fix(h5): 修复h5下的pageScrollTo函数功能
  packages/taro-h5/src/api/scroll/index.js
Labels: V-3

#8113 fix(taro-components): fix radio component disabled property doesn't work in h5 environment (#8017)
  packages/taro-components/src/components.d.ts
  packages/taro-components/src/components/radio/radio.tsx
  packages/taro-components/types/components.d.ts
Labels: V-3

#8260 fix(api): 补全支付宝小程序 getPhoneNumber api，fix #8177
  packages/taro-api/src/native-apis.js
Labels: V-3

#8184 补充uploadFile的timeout,fileName参数功能
  packages/taro-h5/src/api/fileTransfer/uploadFile.js
Labels: V-3

#8262 docs: 更新 RN 端构建APP, 加载 bundle 及静态资源步骤
  docs/config-detail.md
  versioned_docs/version-3.x/react-native.md
Labels: A-docs, T-rn

#8265 chore(release): publish 3.2.0-canary.3
  lerna.json
  packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/package.json
  packages/babel-plugin-transform-taroapi/package.json
  packages/babel-preset-taro/package.json
  packages/babel-preset-taro/rn/index.js
  packages/babel-preset-taro/yarn.lock
  packages/css-to-react-native/package.json
  packages/eslint-config-taro/package.json
  packages/eslint-plugin-taro/package.json
  packages/postcss-plugin-constparse/package.json
  packages/postcss-pxtransform/package.json
  packages/shared/package.json
  packages/stylelint-config-taro-rn/package.json
  packages/stylelint-taro-rn/package.json
  packages/taro-api/package.json
  packages/taro-cli/package.json
  packages/taro-cli/src/cli.ts
  packages/taro-cli/src/commands/build.ts
  packages/taro-components-rn/package.json
  packages/taro-components/package.json
  packages/taro-extend/package.json
  packages/taro-h5/package.json
  packages/taro-helper/package.json
  packages/taro-loader/package.json
  packages/taro-mini-runner/package.json
  packages/taro-react/package.json
  packages/taro-rn-runner/package.json
  packages/taro-rn-runner/src/config/conditional-file-store.ts
  packages/taro-rn-runner/src/config/terminal-reporter.ts
  packages/taro-rn-runner/src/index.ts
  packages/taro-rn-runner/yarn.lock
  packages/taro-rn-style-transformer/package.json
  packages/taro-rn-transformer/package.json
  packages/taro-rn/package.json
  packages/taro-router-rn/package.json
  packages/taro-router/package.json
  packages/taro-runner-utils/package.json
  packages/taro-runtime-rn/package.json
  packages/taro-runtime/package.json
  packages/taro-service/package.json
  packages/taro-webpack-runner/package.json
  packages/taro-with-weapp/package.json
  packages/taro/package.json
  packages/taroize/package.json
Labels: T-rn, V-3

#8259 fix(runtime): 修复短期内重新开启小程序白屏，fix #8103
  packages/taro-runtime/src/dsl/common.ts
Labels: V-3

#8284 refactor(api): 重构跳转预加载 API
  packages/taro-runtime/src/current.ts
  packages/taro-runtime/src/dsl/instance.ts
  packages/taro/apis/alipay.js
  packages/taro/apis/jd.js
  packages/taro/apis/qq.js
  packages/taro/apis/tt.js
  packages/taro/apis/wx.js
  packages/taro/types/api/base/index.d.ts
  packages/taro/types/taro.component.d.ts
  packages/taro/types/taro.extend.d.ts
Labels: V-3

#8289 chore(runtime): 页面onUnmount的事件改为同步触发，避免降低微信体验评分
  packages/taro-runtime/src/dsl/common.ts
Labels: V-3

#8340 fix(runtime): 补全 window 对象的关键属性, fix #8327
  packages/taro-runtime/src/bom/window.ts
Labels: V-3
