Repository NervJS/taro, pull requests merged in 2021-01, with the labels that each got.

#8413 feat(runtime): 静态 html 解析器支持解析 style 标签
  .eslintrc.js
  package.json
  packages/taro-runtime/__tests__/html.spec.js
  packages/taro-runtime/jest.config.js
  packages/taro-runtime/src/__tests__/.gitignore
  packages/taro-runtime/src/__tests__/dom.spec.js
  packages/taro-runtime/src/__tests__/event.spec.js
  packages/taro-runtime/src/__tests__/exports.spec.js
  packages/taro-runtime/src/__tests__/html.spec.js
  packages/taro-runtime/src/__tests__/nerv.spec.js
  packages/taro-runtime/src/__tests__/react.spec.js
  packages/taro-runtime/src/__tests__/style.spec.js
  packages/taro-runtime/src/__tests__/utils.js
  packages/taro-runtime/src/__tests__/vue.spec.js
  packages/taro-runtime/src/dom/html/parser.ts
  packages/taro-runtime/src/dom/html/style.ts
  packages/taro-runtime/src/dom/style.ts
  packages/taro/html.css
  yarn.lock
Labels: V-3

#8372 fix(runtime): 修复 custom-wrapper 若干问题
  packages/shared/src/template.ts
  packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/jd.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/nerv.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap
  packages/taro-mini-runner/src/plugins/MiniPlugin.ts
Labels: V-3

#8443 fix(mini-runner): 修复 app 样式打包错误的问题
  packages/taro-mini-runner/src/plugins/MiniPlugin.ts
Labels: V-3

#8444 fix(runtime): 在微信中clearTimeout要绑定global，fix #7749
  packages/taro-runtime/src/bom/raf.ts
Labels: V-3

#8449 fix(mini-runner): 修复 Vue3 运行时报错，fix #8426
  packages/taro-mini-runner/src/webpack/build.conf.ts
Labels: V-3

#8460 fix(runtime): 修复使用vant时一系列问题，fix #8407 #8242 #8364
  packages/shared/src/template.ts
  packages/shared/src/utils.ts
  packages/taro-mini-runner/src/webpack/vue3.ts
  packages/taro-runtime/src/dom/event.ts
  packages/taro-runtime/src/dsl/react.ts
  packages/taro-runtime/src/dsl/vue3.ts
  packages/taro-runtime/src/reconciler.ts
Labels: V-3

#8473 feat(runtime): 同步 3.1 修改，让小程序 app 对象上可以挂载自定义属性
  packages/taro-runtime/src/dsl/instance.ts
  packages/taro-runtime/src/dsl/react.ts
Labels: V-3

#8521 fix(cli): 修复百度 Text 不显示文本的问题
  packages/taro-cli/src/presets/platforms/swan.ts
  packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap
Labels: V-3

#8539 fix(runtime): 修复react事件回调里没有合并更新的问题，fix #8516
  packages/taro-runtime/src/dom/event.ts
  packages/taro-runtime/src/dsl/react.ts
  packages/taro-runtime/src/reconciler.ts
Labels: V-3

#8551 fix(h5):修复Video组件ref为空而无法暂停播放的问题(NervJS#8550)
  packages/taro-components/src/components/video/video.tsx
Labels: T-h5, V-3

#8568 Feat/blended build
  packages/taro-cli/src/cli.ts
  packages/taro-cli/src/commands/build.ts
  packages/taro-cli/src/presets/commands/build.ts
  packages/taro-cli/src/presets/files/generateProjectConfig.ts
  packages/taro-loader/src/app.ts
  packages/taro-mini-runner/src/plugins/MiniPlugin.ts
  packages/taro-mini-runner/src/utils/index.ts
  packages/taro-mini-runner/src/utils/types.ts
  packages/taro-mini-runner/src/webpack/build.conf.ts
Labels: V-3

#8122 fix(taro-runtime): fix (#7296) problem that the path is empty through the useRouter method in the h5 environment
  packages/taro-runtime/src/dsl/common.ts
Labels: A-router, T-h5, V-3

#8392 fix: onShow should be executed after onLoad.
  packages/taro-runtime/src/dsl/vue3.ts
Labels: V-3

#8408 fix: 修复 h5 使用 pageScrollTo 将 scrollTop 设置为 0 会报错的问题
  packages/taro-h5/src/api/scroll/index.js
Labels: T-h5, V-3
