Repository NervJS/taro, pull requests merged in 2021-08, with the labels that each got.

#9931 fix(webpack-runner): 降级 resolve-url-loader，fix #9863
  packages/taro-components/__tests__/button.spec.js
  packages/taro-webpack-runner/package.json
  packages/taro-webpack-runner/yarn.lock
Labels: V-3

#9907 fix(swiper): 优化 swiper 节点刷新方案
  packages/taro-components-react/package.json
  packages/taro-components-react/src/components/swiper/index.tsx
  packages/taro-components/__tests__/utils.js
  packages/taro-components/package.json
  packages/taro-components/src/components/swiper/swiper.tsx
Labels: V-3

#9954 fix(weapp): 修复分享朋友圈后进入白屏的问题，fix #9899
  packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/jd.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/nerv.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap
  packages/taro-mini-runner/src/webpack/base.conf.ts
  packages/taro-weapp/src/apis.ts
Labels: V-3

#9953 fix(runtime): 优化对 comment 节点的处理，fix #9864
  packages/taro-runtime/src/dom/node.ts
Labels: V-3

#9815 Update live-player.md
  versioned_docs/version-3.x/components/media/live-player.md
Labels: question

#9988 fix(runtime): 修复对 style 标签的解析问题，fix #9885
  packages/taro-runtime/src/__tests__/html.spec.js
  packages/taro-runtime/src/dom-external/inner-html/style.ts
Labels: V-3

#9816 fix(picker): 修复 h5 端 vue 开发下 picker 组件 rangeKey 获取为 undefined 的问题
  packages/taro-components/h5/vue/components/picker.js
Labels: V-3

#9793 fix: the copy function cannot parse newlines
  packages/taro-h5/src/api/clipboard/index.js
Labels: V-3

#10009 feat(weapp): 为 weapp 平台添加 modifyRunnerOpts 钩子，使得小程序的 Taro 配置项得以暴露
  packages/taro-cli/src/presets/platforms/h5.ts
  packages/taro-plugin-html/src/index.ts
  packages/taro-service/src/Kernel.ts
Labels: V-3

#10079 fix(router-rn): if(config.tabbar) 总为true
  packages/taro-router-rn/src/router.ts
Labels: V-3, T-rn

#10082 docs: rn 配置 rn.resolve 描述修改
  docs/config-detail.md
  versioned_docs/version-3.x/config-detail.md
Labels: T-rn

#10081 增加对除 page 页面全局样式补充，npm 包支持需配置 rn.resolve
  packages/taro-rn-supporter/src/taroTransformer.ts
  packages/taro-rn-transformer/src/index.ts
  packages/taro-rn-transformer/src/page.ts
  packages/taro-rn-transformer/src/types/index.ts
  packages/taro-rn-transformer/src/utils.ts
Labels: T-rn

#10146 fix(rn): getSetting, openSetting opt optional
  packages/taro-rn/src/lib/connectSocket/index.ts
  packages/taro-rn/src/lib/connectSocket/socketTask.ts
  packages/taro-rn/src/lib/file.ts
  packages/taro-rn/src/lib/getClipboardData/index.ts
  packages/taro-rn/src/lib/getLocation/index.ts
  packages/taro-rn/src/lib/getStorageInfo/index.ts
  packages/taro-rn/src/lib/getSystemInfo/index.ts
  packages/taro-rn/src/lib/makePhoneCall/index.ts
  packages/taro-rn/src/lib/media.ts
  packages/taro-rn/src/lib/network.ts
  packages/taro-rn/src/lib/openUrl/index.ts
  packages/taro-rn/src/lib/permission.ts
  packages/taro-rn/src/lib/removeStorage/index.ts
  packages/taro-rn/src/lib/request/index.ts
  packages/taro-rn/src/lib/setClipboardData/index.ts
  packages/taro-rn/src/lib/showActionSheet/index.tsx
  packages/taro-rn/src/lib/showModal/index.tsx
  packages/taro-rn/src/lib/showModal/toast.tsx
  packages/taro-rn/src/lib/vibrate.ts
Labels: V-3, T-rn
