Repository NervJS/taro, pull requests merged in 2021-09, with the labels that each got.

#10230 fix(alipay): 补充导出钉钉小程序插件需要的内容，fix #10075
  packages/taro-alipay/src/runtime-utils.ts
Labels: V-3

#10207 修复Image组件不支持为 img 标签额外增加属性
  packages/taro-components/src/components/audio/audio.tsx
  packages/taro-components/src/components/canvas/canvas.tsx
  packages/taro-components/src/components/checkbox/checkbox.tsx
  packages/taro-components/src/components/image/image.tsx
  packages/taro-components/src/components/input/input.tsx
  packages/taro-components/src/components/radio/radio.tsx
  packages/taro-components/src/components/switch/switch.tsx
  packages/taro-components/src/components/textarea/textarea.tsx
  packages/taro-components/src/components/video/video.tsx
Labels: V-3

#10289 fix(shared): 修复 @tarojs/shared processApis 方法当 config.isOnlyPromisify…
  packages/shared/src/native-apis.ts
  packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/jd.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/nerv.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap
Labels: question, V-3

#10283 fix(rn): 新增及修复 getSystemInfo API 中部分字段
  packages/taro-rn/package.json
  packages/taro-rn/src/lib/getSystemInfoSync/index.ts
  packages/taro-rn/yarn.lock
Labels: V-3, T-rn

#10316 fix(router-rn): fix rn router memory leak & remove redirect animate
  packages/taro-components-rn/src/components/Button/index.tsx
  packages/taro-router-rn/src/rootNavigation.ts
  packages/taro-router-rn/src/router.ts
  packages/taro-router-rn/src/utils/index.ts
  packages/taro-runtime-rn/src/page.ts
Labels: V-3, T-rn
