Repository NervJS/taro, pull requests merged in 2021-04, with the labels that each got.

#9031 Feat apis & comps
  package.json
  packages/babel-preset-taro/yarn.lock
  packages/eslint-config-taro/package.json
  packages/eslint-config-taro/yarn.lock
  packages/taro-alipay/src/apis-list.ts
  packages/taro-api/rollup.config.js
  packages/taro-cli/yarn.lock
  packages/taro-components-rn/yarn.lock
  packages/taro-components/src/components.d.ts
  packages/taro-components/yarn.lock
  packages/taro-h5/rollup.config.js
  packages/taro-h5/yarn.lock
  packages/taro-helper/yarn.lock
  packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/jd.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/nerv.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap
  packages/taro-mini-runner/yarn.lock
  packages/taro-rn-runner/yarn.lock
  packages/taro-rn-style-transformer/yarn.lock
  packages/taro-rn-supporter/yarn.lock
  packages/taro-rn/yarn.lock
  packages/taro-router-rn/yarn.lock
  packages/taro-router/package.json
  packages/taro-router/yarn.lock
  packages/taro-runner-utils/yarn.lock
  packages/taro-utils/rollup.config.js
  packages/taro-weapp/src/apis-list.ts
  packages/taro-weapp/src/components-react.ts
  packages/taro-weapp/src/components.ts
  packages/taro-weapp/types/components-react.d.ts
  packages/taro-weapp/types/components.d.ts
  packages/taro-webpack-runner/package.json
  packages/taro-webpack-runner/src/index.ts
  packages/taro-webpack-runner/src/util/index.ts
  packages/taro-webpack-runner/yarn.lock
  packages/taroize/yarn.lock
  yarn.lock
Labels: V-3

#9034 fix(mini-runner): vue3 slot not distributing content
  packages/taro-mini-runner/src/webpack/vue3.ts
Labels: V-3

#8823 fix(swan):百度小程序componentDidShow 获取props为空
  packages/taro-swan/src/component.js
Labels: V-2

#9180 fix(components): 修复虚拟列表抖动问题 fix #8936
  packages/taro-components/virtual-list/react/createListComponent.js
Labels: V-3

#9173 fix(router): 修复点击浏览器返回按钮异常的问题
  packages/taro-router/src/router.ts
Labels: V-3

#9170 fix(runner): 小程序编译默认使用 dart-sass，close #8257 #9151
  package.json
  packages/babel-preset-taro/package.json
  packages/babel-preset-taro/yarn.lock
  packages/eslint-config-taro/yarn.lock
  packages/taro-cli/yarn.lock
  packages/taro-components-rn/yarn.lock
  packages/taro-components/yarn.lock
  packages/taro-helper/package.json
  packages/taro-helper/yarn.lock
  packages/taro-loader/yarn.lock
  packages/taro-mini-runner/package.json
  packages/taro-mini-runner/src/__tests__/setup/index.ts
  packages/taro-mini-runner/src/webpack/chain.ts
  packages/taro-mini-runner/yarn.lock
  packages/taro-rn-runner/yarn.lock
  packages/taro-rn-style-transformer/yarn.lock
  packages/taro-rn-supporter/yarn.lock
  packages/taro-rn/yarn.lock
  packages/taro-router-rn/yarn.lock
  packages/taro-runner-utils/babel.config.js
  packages/taro-runner-utils/package.json
  packages/taro-runner-utils/src/scss.ts
  packages/taro-runner-utils/yarn.lock
  packages/taro-webpack-runner/package.json
  packages/taro-webpack-runner/src/__tests__/__snapshots__/vue.spec.ts.snap
  packages/taro-webpack-runner/src/__tests__/setup/index.ts
  packages/taro-webpack-runner/src/util/chain.ts
  packages/taro-webpack-runner/yarn.lock
  packages/taro-with-weapp/package.json
  packages/taro-with-weapp/yarn.lock
  yarn.lock
Labels: V-3

#9192 fix(runtime): 修复多次跳转相同参数的同一页面时生命周期不触发的问题，fix #8874
  packages/taro-runtime/src/dsl/common.ts
Labels: V-3

#9063 fix(types): 修复CanvasProps中onTouch系列函数的类型
  packages/taro-components/types/Canvas.d.ts
  packages/taro-components/types/common.d.ts
Labels: A-typings, V-3

#9211 fix(mini-runner): 修复 sass 解析 alias 失败，fix #9207
  packages/taro-mini-runner/src/webpack/chain.ts
  packages/taro-webpack-runner/src/util/chain.ts
Labels: V-3

#9206 fix(runner): 更新 less 及 loader 到最新版本，fix #9079
  packages/taro-mini-runner/package.json
  packages/taro-mini-runner/yarn.lock
  packages/taro-webpack-runner/package.json
  packages/taro-webpack-runner/yarn.lock
Labels: V-3
