Repository NervJS/taro, pull requests merged in 2021-02, with the labels that each got.

#8599 修复 incrementId 调用错误；修复 customWrapper 优化失效
  packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/jd.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/nerv.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap
  packages/taro-mini-runner/src/template/custom-wrapper.ts
  packages/taro-runtime/src/dom/root.ts
  packages/taro-runtime/src/dsl/common.ts
Labels: V-3

#8485 fix(h5): 在同一页面多次chooseImage时，更新multiple属性
  packages/taro-h5/src/api/image/chooseImage.js
Labels: T-h5, V-3

#8366 Update chooseImage.js
  packages/taro-h5/src/api/image/chooseImage.js
Labels: T-h5, V-3

#8514 fix(components): 修复form组件设置h5原生属性无效的问题
  packages/taro-components/src/components/form/index.js
  packages/taro-components/types/Form.d.ts
Labels: V-2

#8562 fix(virtual-list): scrollTo 调用后会额外触发一次 render，并导致 scrollView 回到顶部(#8560)
  packages/taro-components/virtual-list/react/createListComponent.js
Labels: A-components, T-h5, V-3

#8402 fix: frameCnt lower than 1
  packages/taro-h5/src/api/utils/index.js
Labels: A-api, T-h5, V-3

#8654 fix(router): 修复Taro.redirectTo和Taro.reLaunch方法导致多次componentDidShow的问题
  packages/taro-router/src/router/route.tsx
Labels: V-2

#8538 fix(router): 修复页面首次加载时调用Taro.reLaunch会跳转到空页面
  packages/taro-router/src/apis/index.ts
Labels: V-2

#8642 fix(components-rn): 修复 rn 下 video onError 报错
  packages/taro-components-rn/src/components/Video/index.tsx
Labels: T-rn

#8753 fix(mini-runner): 修复react/jsx-runtime报错，fix #8750
  packages/taro-mini-runner/src/webpack/build.conf.ts
Labels: V-3

#8755 fix(runtime): 修复Vue3 style设置css变量解析错误问题，fix #8736
  packages/taro-runtime/src/dom/style.ts
Labels: V-3

#8754 fix(weapp): 为 Video 组件补充广告相关事件
  packages/babel-preset-taro/yarn.lock
  packages/eslint-config-taro/yarn.lock
  packages/eslint-plugin-taro/yarn.lock
  packages/postcss-plugin-constparse/yarn.lock
  packages/postcss-pxtransform/yarn.lock
  packages/taro-cli/yarn.lock
  packages/taro-components/yarn.lock
  packages/taro-h5/yarn.lock
  packages/taro-helper/yarn.lock
  packages/taro-loader/yarn.lock
  packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/jd.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/nerv.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap
  packages/taro-mini-runner/yarn.lock
  packages/taro-react/yarn.lock
  packages/taro-router/yarn.lock
  packages/taro-runner-utils/yarn.lock
  packages/taro-runtime/src/dom/event.ts
  packages/taro-runtime/yarn.lock
  packages/taro-service/yarn.lock
  packages/taro-weapp/src/components.ts
  packages/taro-weapp/types/components.d.ts
  packages/taro-webpack-runner/yarn.lock
  packages/taro-with-weapp/yarn.lock
  packages/taroize/yarn.lock
Labels: V-3
