Repository NervJS/taro, pull requests merged in 2021-11, with the labels that each got.

#10517 feat(harmony): 新增input组件
  packages/taro-harmony/src/components/components-harmony/input/index.hml
  packages/taro-harmony/src/components/components-harmony/input/index.js
  packages/taro-harmony/src/components/index.ts
  packages/taro-harmony/src/template.ts
Labels: T-harmony

#10442 Feat/harmony progress com
  packages/taro-harmony/src/components/components-harmony/progress/index.css
  packages/taro-harmony/src/components/components-harmony/progress/index.hml
  packages/taro-harmony/src/components/components-harmony/progress/index.js
  packages/taro-harmony/src/components/index.ts
Labels: T-harmony

#10533 feat(harmony): 新增 slider 组件
  packages/taro-harmony/src/components/components-harmony/slider/index.hml
  packages/taro-harmony/src/components/components-harmony/slider/index.js
  packages/taro-harmony/src/components/index.ts
Labels: T-harmony

#10561 Harmony comp radio
  packages/taro-harmony/src/components/components-harmony/radio-group/index.hml
  packages/taro-harmony/src/components/components-harmony/radio-group/index.js
  packages/taro-harmony/src/components/components-harmony/radio/index.hml
  packages/taro-harmony/src/components/components-harmony/radio/index.js
  packages/taro-harmony/src/components/index.ts
Labels: T-harmony

#10565 重新提交 image 组件
  packages/taro-harmony/src/components/components-harmony/image/index.css
  packages/taro-harmony/src/components/components-harmony/image/index.hml
  packages/taro-harmony/src/components/components-harmony/image/index.js
  packages/taro-harmony/src/components/index.ts
Labels: T-harmony

#10571 feat(harmony): 增加 pageScrollTo API
  packages/taro-harmony/src/apis/apis.ts
  packages/taro-harmony/src/apis/page/index.ts
Labels: T-harmony

#10572 feat(harmony): 新增Webview组件
  packages/taro-harmony/src/components/components-harmony/web-view/index.hml
  packages/taro-harmony/src/components/components-harmony/web-view/index.js
  packages/taro-harmony/src/template.ts
Labels: T-harmony

#10482 fix(rn): css-transform
  packages/css-to-react-native/__tests__/index.spec.js
  packages/css-to-react-native/src/css-to-react-native/TokenStream.js
  packages/css-to-react-native/src/css-to-react-native/index.js
  packages/css-to-react-native/src/css-to-react-native/tokenTypes.js
  packages/css-to-react-native/src/css-to-react-native/transforms/flex.js
  packages/css-to-react-native/src/css-to-react-native/transforms/font.js
  packages/css-to-react-native/src/css-to-react-native/transforms/textDecoration.js
  packages/css-to-react-native/src/css-to-react-native/transforms/transform.js
  packages/css-to-react-native/src/css-to-react-native/transforms/util.js
  packages/css-to-react-native/src/index.js
Labels: T-rn

#10453 Feat/harmony interactive api
  packages/taro-harmony/src/apis/apis.ts
  packages/taro-harmony/src/apis/interactive/index.ts
  packages/taro-harmony/src/program.ts
Labels: T-harmony

#10548 Feat/harmony textera
  packages/taro-harmony/src/components/components-harmony/textarea/index.hml
  packages/taro-harmony/src/components/components-harmony/textarea/index.js
  packages/taro-harmony/src/components/index.ts
Labels: T-harmony

#9495 fix(h5): 修复h5环境下previewImage预览图片时,当图片高度大于屏幕高度时,图片展示不全无法上下滑动
  packages/taro-h5/src/api/image/previewImage.js
Labels: V-3

#10629 Feat/harmony picker
  packages/taro-harmony/src/components/components-harmony/picker/index.hml
  packages/taro-harmony/src/components/components-harmony/picker/index.js
  packages/taro-harmony/src/components/index.ts
  packages/taro-harmony/src/template.ts
Labels: T-harmony

#10623 fix(h5): add disabled prop to checkbox #8500
  packages/taro-components/src/components/checkbox/checkbox.tsx
Labels: T-h5

#10441 feat(harmony): 新增 button 组件
  packages/taro-harmony/src/components/components-harmony/button/index.css
  packages/taro-harmony/src/components/components-harmony/button/index.hml
  packages/taro-harmony/src/components/components-harmony/button/index.js
  packages/taro-harmony/src/template.ts
Labels: T-harmony

#10620 fix(component): swiper 播放 next-margin 参数优化
  packages/taro-components/src/components/swiper/swiper.tsx
Labels: T-h5

#10249 fix(runtime): page.onLoad, page.onShow
  packages/taro-runtime/src/dsl/common.ts
Labels: question, V-3

#10614 feat(harmony): 完成用户相关api
  packages/taro-harmony/src/apis/apis.ts
  packages/taro-harmony/src/apis/user/index.ts
  packages/taro-harmony/src/program.ts
Labels: T-harmony

#10510 fix(stencil): 修复 stencil 组件的 slot 问题，fix #10365
  packages/taro-components/__tests__/slider.spec.js
  packages/taro-components/package.json
  packages/taro-components/src/components/view/view.tsx
  packages/taro-components/yarn.lock
Labels: V-3

#10575 Add KWAI Env
  .eslintrc.js
  packages/taro-api/src/env.js
Labels: question, V-3

#10657 fix(types): 优化类型实体写法 fix #10652
  packages/taro/types/global.d.ts
  packages/taro/types/taro.extend.d.ts
Labels: A-typings

#10697 fix(runtime): 修复使用 recoil 报错的问题，fix #10119
  packages/taro-runtime/src/bom/window.ts
Labels: V-3

#10609 fix(h5): input component focus problem #10303
  packages/taro-components/src/components/input/input.tsx
Labels: question, V-3, T-h5

#10702 fix(components): 修复 Vue2 组件的 nativeProps 失效的问题，fix #10689
  packages/taro-components/h5/vue/createComponent.js
  packages/taro-components/h5/vue/createFormsComponent.js
Labels: V-3

#10606 feat(h5): cover-image组件
  packages/taro-components/__tests__/cover-image.spec.js
  packages/taro-components/__tests__/unimplemented.spec.js
  packages/taro-components/src/components/cover-image/cover-image.tsx
  packages/taro-components/src/components/cover-image/style/index.scss
  packages/taro-components/src/components/cover-view/cover-image.tsx
Labels: question, V-3, T-h5

#10713 feat(weapp): 增加对 getLocalIPAddress API 的支持，fix #10631
  packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/nerv.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap
  packages/taro-weapp/src/apis-list.ts
  packages/taro/types/api/device/network.d.ts
Labels: V-3

#10726 feat(types): 补齐 env 导出对象类型 #10652
  packages/taro/types/compile.d.ts
  packages/taro/types/global.d.ts
  packages/taro/types/taro.extend.d.ts
Labels: A-typings

#10727 fix(rn): app.config 修改后未更新
  packages/taro-rn-runner/src/config/conditional-file-store.ts
Labels: P-1, V-3, T-rn

#10738 feat(rn-style-transformer): 用户安装node-sass情况使用node-sass && 锁定sass版本
  packages/taro-rn-style-transformer/__tests__/config.spec.js
  packages/taro-rn-style-transformer/__tests__/index.spec.js
  packages/taro-rn-style-transformer/__tests__/platform.spec.js
  packages/taro-rn-style-transformer/__tests__/styles/c.rn.scss
  packages/taro-rn-style-transformer/__tests__/styles/c.scss
  packages/taro-rn-style-transformer/__tests__/styles/d.rn.scss
  packages/taro-rn-style-transformer/__tests__/styles/d.scss
  packages/taro-rn-style-transformer/package.json
  packages/taro-rn-style-transformer/src/transforms/sass.ts
  packages/taro-rn-style-transformer/yarn.lock
Labels: T-rn

#10708 Feat/harmony picker view
  packages/taro-harmony/src/components/components-harmony/picker-view-column/index.hml
  packages/taro-harmony/src/components/components-harmony/picker-view-column/index.js
  packages/taro-harmony/src/components/components-harmony/picker-view/index.hml
  packages/taro-harmony/src/components/components-harmony/picker-view/index.js
  packages/taro-harmony/src/components/index.ts
Labels: T-harmony

#10739 feat(rn): support backgroundTextStyle setting
  packages/taro-runtime-rn/src/page.ts
Labels: V-3, T-rn

#10664 Feat/harmony navigator com
  packages/taro-harmony/src/components/components-harmony/navigator/index.css
  packages/taro-harmony/src/components/components-harmony/navigator/index.hml
  packages/taro-harmony/src/components/components-harmony/navigator/index.js
  packages/taro-harmony/src/components/components-harmony/utils/index.js
Labels: T-harmony

#10618 feat(harmony): add system api in taro-harmony
  .vscode/settings.json
  packages/taro-harmony/src/apis/apis.ts
  packages/taro-harmony/src/apis/system/index.ts
Labels: T-harmony

#10775 feat(rn-style-transformer): postcss 支持插件自定义
  packages/taro-rn-style-transformer/src/transforms/postcss.ts
Labels: T-rn
