Repository NervJS/taro, pull requests merged in 2021-12, with the labels that each got.

#10665 Harmony xueshuai
  packages/taro-harmony/src/apis/apis.ts
  packages/taro-harmony/src/apis/geolocation/index.ts
Labels: T-harmony

#10807 fix: update rn rich text height on load again
  packages/taro-components-rn/__tests__/__snapshots__/richText.spec.tsx.snap
  packages/taro-components-rn/src/components/RichText/index.tsx
Labels: V-3, T-rn

#10820 fix(harmony): 修复 slider 组件 value不更新&溢出问题
  packages/taro-harmony/src/components/components-harmony/slider/index.hml
  packages/taro-harmony/src/components/components-harmony/slider/index.js
  packages/taro-harmony/src/components/index.ts
Labels: T-harmony

#10640 Feat/harmony form
  packages/taro-harmony/src/components/components-harmony/button/index.hml
  packages/taro-harmony/src/components/components-harmony/button/index.js
  packages/taro-harmony/src/components/components-harmony/checkbox/index.hml
  packages/taro-harmony/src/components/components-harmony/checkbox/index.js
  packages/taro-harmony/src/components/components-harmony/form/index.hml
  packages/taro-harmony/src/components/components-harmony/form/index.js
  packages/taro-harmony/src/components/components-harmony/input/index.hml
  packages/taro-harmony/src/components/components-harmony/input/index.js
  packages/taro-harmony/src/components/components-harmony/radio/index.hml
  packages/taro-harmony/src/components/components-harmony/radio/index.js
Labels: T-harmony

#10822 Harmony network
  packages/taro-harmony/src/apis/apis.ts
  packages/taro-harmony/src/apis/network/downloadFile.ts
  packages/taro-harmony/src/apis/network/index.ts
  packages/taro-harmony/src/apis/network/request.ts
  packages/taro-harmony/src/apis/network/uploadFile.ts
  packages/taro-harmony/src/apis/network/webSocket.ts
Labels: T-harmony

#10793 Feat rn add svg support
  packages/taro-components-rn/package.json
  packages/taro-components-rn/src/components/Image/PropsType.tsx
  packages/taro-components-rn/src/components/Image/index.tsx
  packages/taro-components-rn/yarn.lock
  packages/taro-components/types/Image.d.ts
  packages/taro-rn-supporter/package.json
  packages/taro-rn-supporter/src/Support.ts
  packages/taro-rn-supporter/src/defaults.ts
  packages/taro-rn-supporter/src/taroTransformer.ts
  packages/taro-rn-supporter/src/types/index.ts
  packages/taro-rn-supporter/yarn.lock
Labels: V-3, T-rn

#10843 fix(harmony): input组件用作radio时，同一group的item，name必须相同，这里使用groupId作为name
  packages/taro-harmony/src/components/components-harmony/radio/index.hml
  packages/taro-harmony/src/components/components-harmony/radio/index.js
Labels: T-harmony

#10871 fix(shared/runtime): 修复 vant weapp 兼容问题，fix #10337
  packages/shared/src/template.ts
  packages/taro-runtime/src/dom/element.ts
Labels: V-3

#10866 fix(components-rn): picker null props bug
  packages/taro-components-rn/src/components/Picker/date.tsx
  packages/taro-components-rn/src/components/Picker/time.tsx
Labels: V-3, T-rn

#10812 fix: taro-plugin-html genAttrMapFnFromDir
  packages/taro-plugin-html/src/constant.ts
Labels: question

#10864 fix(swan): 修复百度小程序 Text 嵌套不显示的问题，fix #10829
  packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap
  packages/taro-swan/src/template.ts
Labels: V-3

#10876 feat(rn): add bundle preview
  packages/taro-rn-runner/package.json
  packages/taro-rn-runner/src/config/preview.ts
  packages/taro-rn-runner/src/index.ts
  packages/taro-rn-runner/src/utils.ts
Labels: V-3, T-rn

#10887 Fix/html style
  packages/taro-runtime/src/__tests__/html.spec.js
  packages/taro-runtime/src/dom-external/inner-html/style.ts
Labels: V-3

#10888 fix( alipay): 兼容支付宝 2.0 构建，fix #10162
  packages/shared/src/template.ts
  packages/taro-alipay/src/template.ts
  packages/taro-mini-runner/src/plugins/TaroNormalModulesPlugin.ts
Labels: V-3

#10839 fix: 修复事件调用 preventDefault 后 defaultPrevented 值不存在的问题
  packages/taro-alipay/src/create-component.js
  packages/taro-jd/src/create-component.js
  packages/taro-qq/src/create-component.js
  packages/taro-quickapp/src/create-component.js
  packages/taro-swan/src/create-component.js
  packages/taro-tt/src/create-component.js
  packages/taro-weapp/src/create-component.js
Labels: V-2

#10909 feat(types): add Events fix #10880
  packages/taro/types/taro.extend.d.ts
Labels: A-typings

#10895 fix(rn): swiper support circular
  packages/taro-components-rn/.eslintrc.js
  packages/taro-components-rn/src/components/Swiper/carousel.tsx
  packages/taro-components-rn/src/components/Swiper/pagination.tsx
Labels: V-3, T-rn

#10936 Update image.tsx
  packages/taro-components/src/components/image/image.tsx
Labels: A-components, V-3, T-h5

#10938 feat(babel): 动态加载 tree shaking for pwa fix #10937
  packages/babel-preset-taro/index.js
Labels: A-babel, T-h5

#10963 fix(h5): createAnimation 部分 API 错误修复
  packages/taro-h5/src/api/base/system/index.ts
  packages/taro-h5/src/api/device/accelerometer.ts
  packages/taro-h5/src/api/device/compass.ts
  packages/taro-h5/src/api/device/motion.ts
  packages/taro-h5/src/api/location/index.ts
  packages/taro-h5/src/api/network/websocket/index.ts
  packages/taro-h5/src/api/storage/index.ts
  packages/taro-h5/src/api/ui/animation/index.ts
  packages/taro-h5/src/api/ui/pull-down-refresh.ts
  packages/taro-h5/src/api/utils/index.ts
  packages/taro-h5/src/api/wxml/nodesRef.ts
  packages/taro-h5/src/api/wxml/selectorQuery.ts
  packages/taro/types/api/ui/animation.d.ts
Labels: A-api, V-3, T-h5

#10962 fix(rn): swiper selectIndex updated when props change
  packages/taro-components-rn/src/components/Swiper/carousel.tsx
Labels: V-3, T-rn

#10964 fix(alipay): fix #10162
  packages/taro-alipay/src/template.ts
Labels: T-alipay

#10969 feat: scancode has fullscreen as default
  packages/taro-rn/.eslintrc.js
  packages/taro-rn/src/lib/scanCode/index.tsx
Labels: V-3, T-rn

#10970 fix(runtime-rn): update route from getCurrentPages
  packages/taro-runtime-rn/src/page.ts
Labels: V-3, T-rn

#10977 fix: swiper 1 itme & input padding
  packages/taro-components-rn/src/components/Input/index.tsx
  packages/taro-components-rn/src/components/Swiper/PropsType.tsx
  packages/taro-components-rn/src/components/Swiper/carousel.tsx
Labels: A-components, T-rn
