Repository NervJS/taro, pull requests merged in 2021-07, with the labels that each got.

#9670 fix(alipay): 修复 Vue3 使用 Swiper 时出现空白页的问题，fix #9618
  packages/taro-alipay/src/template.ts
  packages/taro-alipay/types/template.d.ts
  packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap
Labels: V-3

#9679 fix(runtime): 修复 Vue3 生命周期触发问题，fix #9614
  packages/taro-runtime/src/dsl/vue3.ts
Labels: V-3

#9690 fix(swan): 修复删除 input 内容时光标跳动的问题，fix #6632
  packages/shared/src/template.ts
  packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/jd.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/nerv.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap
  packages/taro-swan/src/template.ts
  packages/taro-swan/types/template.d.ts
Labels: V-3

#9693 Revert "fix(runtime): 修复 Vue3 生命周期触发问题，fix #9614"
  packages/taro-runtime/src/dsl/vue3.ts
Labels: V-3

#5297 锁定版本
  packages/taro-async-await/package.json
Labels: V-2

#9706 fix(jd): 补全Button的 bindgetphonenumber 属性，fix #9633
  packages/taro-jd/src/components.ts
  packages/taro-jd/types/components.d.ts
  packages/taro-mini-runner/src/__tests__/__snapshots__/jd.spec.ts.snap
Labels: V-3

#9677 fix(swan): 解决百度端调用Taro.login真机上无效的问题
  packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap
  packages/taro-swan/src/apis.ts
  packages/taro-swan/types/apis.d.ts
  packages/taro/types/api/network/mdns.d.ts
  packages/taro/types/api/network/websocket.d.ts
Labels: V-3, question

#9796 fix(components): 修复 Vue3 使用 input 组件时 v-model 失效的问题，fix #9775
  packages/taro-components/h5/vue3/createFormsComponent.js
  packages/taro-components/src/components/input/input.tsx
Labels: V-3

#9582 解决百度端template嵌套ad导致视频前贴后贴广告无法播放的问题
  packages/taro-swan/src/template.ts
Labels: V-3, question

#9789 feat(plugin): 新增支持 react-devtools 插件
  .eslintignore
  lerna.json
  package.json
  packages/shared/src/native-apis.ts
  packages/taro-alipay/src/apis.ts
  packages/taro-alipay/types/apis.d.ts
  packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/jd.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/nerv.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap
  packages/taro-plugin-react-devtools/index.js
  packages/taro-plugin-react-devtools/package.json
  packages/taro-plugin-react-devtools/rollup.config.js
  packages/taro-plugin-react-devtools/src/backend/index.js
  packages/taro-plugin-react-devtools/src/index.ts
  packages/taro-plugin-react-devtools/src/loader.ts
  packages/taro-plugin-react-devtools/src/runtime.ts
  packages/taro-plugin-react-devtools/src/websocket.ts
  packages/taro-plugin-react-devtools/tsconfig.json
  packages/taro-plugin-react-devtools/yarn.lock
  packages/taro-react/src/reconciler.ts
  yarn.lock
Labels: V-3

#9841 fix(runtime): 修复@tarojs/plugin-inject使用报错的问题，fix #9783
  packages/taro-runtime/src/hooks.ts
Labels: V-3

#9660 fix(babel-preset-taro): fix #9659
  packages/babel-preset-taro/README.md
  packages/babel-preset-taro/__tests__/index.spec.js
  packages/babel-preset-taro/index.js
  packages/babel-preset-taro/package.json
  packages/babel-preset-taro/yarn.lock
Labels: F-vue3, V-3, question

#9529 fix(swan): View 标签支持 flex 布局
  packages/shared/__tests__/shared.spec.ts
  packages/shared/src/template.ts
  packages/shared/src/utils.ts
  packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/jd.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/nerv.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap
  packages/taro-swan/src/program.ts
  packages/taro-swan/src/runtime-utils.ts
  packages/taro-swan/src/template.ts
  packages/taro-swan/types/runtime-utils.d.ts
  packages/taro-swan/types/template.d.ts
Labels: V-3

#9897 fix: 修复 css module 变量多次赋值判断失效
  packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/__tests__/index.spec.js
  packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/src/index.ts
Labels: T-rn

#9922 feat(vue): 支持使用 Vue DevTools
  .eslintignore
  lerna.json
  packages/taro-plugin-vue-devtools/index.js
  packages/taro-plugin-vue-devtools/package.json
  packages/taro-plugin-vue-devtools/rollup.config.js
  packages/taro-plugin-vue-devtools/src/backend/backend.LICENSE.txt
  packages/taro-plugin-vue-devtools/src/backend/build/backend.js
  packages/taro-plugin-vue-devtools/src/backend/build/hook.js
  packages/taro-plugin-vue-devtools/src/backend/index.js
  packages/taro-plugin-vue-devtools/src/index.ts
  packages/taro-plugin-vue-devtools/src/runtime.ts
  packages/taro-plugin-vue-devtools/src/socket-io.ts
  packages/taro-plugin-vue-devtools/src/websocket.ts
  packages/taro-plugin-vue-devtools/tsconfig.json
  packages/taro-runtime/src/bom/window.ts
  packages/taro-runtime/src/constants/identifiers.ts
  packages/taro-runtime/src/dom/document.ts
  packages/taro-runtime/src/dom/element.ts
  packages/taro-runtime/src/dom/node.ts
  packages/taro-runtime/src/hooks.ts
  packages/taro-runtime/src/interface/hooks.ts
Labels: V-3
