Repository NervJS/taro, pull requests merged in 2022-04, with the labels that each got.

#11427 fix(router): 修复设置 basename 后不跳转默认路由的问题
  packages/taro-router/src/router/index.ts
Labels: T-h5

#11582 feat(rn): mv unimodules deps
  packages/taro-components-rn/package.json
  packages/taro-rn/package.json
  packages/taro-router-rn/package.json
  yarn.lock
Labels: T-rn

#11455 fix(components): Image heightFix no work
  packages/taro-components/src/components/image/image.tsx
  packages/taro-components/src/components/image/style/index.scss
Labels: A-components, T-h5

#11537 fix(h5): 修复vue3使用 ref 引用时未引用原生组件实例
  packages/taro-components/h5/vue3/components/icon.js
  packages/taro-components/h5/vue3/components/image.js
  packages/taro-components/h5/vue3/components/scroll-view.js
  packages/taro-components/h5/vue3/components/text.js
  packages/taro-components/h5/vue3/createComponent.js
  packages/taro-components/h5/vue3/createFormsComponent.js
  packages/taro-components/h5/vue3/forwardRef.js
Labels: T-h5

#8815 fix(taro-h5): chooseImage 支持 sourceType
  packages/taro-h5/src/api/media/image/chooseImage.ts
Labels: A-api, T-h5

#11428 feat(h5) h5的chooseLocation 新增api，支持腾讯地图选点组件的所有api
  package.json
  packages/taro-h5/package.json
  packages/taro-h5/rollup.config.js
  packages/taro-h5/src/api/location/chooseLocation.ts
  packages/taro-router/package.json
  packages/taro-router/rollup.config.js
  packages/taro/types/api/location/index.d.ts
Labels: T-h5

#11598 fix(h5): getImageInfo missing path value
  packages/taro-h5/src/api/media/image/getImageInfo.ts
Labels: A-api, E-easy, T-h5

#11594 refactor(rn): 实现 rn 端 input 组件中 placeholder color 的设置
  packages/taro-components-rn/src/components/Input/PropsType.tsx
  packages/taro-components-rn/src/components/Input/index.tsx
  packages/taro-components/types/Input.d.ts
Labels: T-rn

#11535 feat(types): update from docs
  packages/taro-components/types/Button.d.ts
  packages/taro-components/types/Input.d.ts
  packages/taro-components/types/KeyboardAccessory.d.ts
  packages/taro-components/types/Picker.d.ts
  packages/taro-components/types/ShareElement.d.ts
  packages/taro-components/types/common.d.ts
  packages/taro-components/virtual-list/react/createListComponent.js
  packages/taro/types/api/ad/index.d.ts
  packages/taro/types/api/canvas/index.d.ts
  packages/taro/types/api/device/network.d.ts
  packages/taro/types/api/network/request.d.ts
  packages/taro/types/api/open-api/authorize.d.ts
  packages/taro/types/api/ui/animation.d.ts
  packages/taro/types/api/worker/index.d.ts
  packages/taro/types/api/wxml/index.d.ts
  packages/taro/types/taro.extend.d.ts
Labels: A-typings

#11628 fix(runner): 修复Vue不能使用module模式css module的问题，#6662
  packages/taro-mini-runner/src/webpack/chain.ts
  packages/taro-webpack-runner/src/util/chain.ts
Labels: V-3

#11616 feat(h5):添加非微信JS-SDK下的getLocation API实现
  packages/taro-h5/__tests__/location/index.test.ts
  packages/taro-h5/__tests__/network/websocket.test.ts
  packages/taro-h5/__tests__/storage/index.test.ts
  packages/taro-h5/__tests__/ui/animation.test.ts
  packages/taro-h5/__tests__/ui/interaction/actionSheet.test.ts
  packages/taro-h5/__tests__/ui/interaction/loading.test.ts
  packages/taro-h5/__tests__/ui/interaction/modal.test.ts
  packages/taro-h5/__tests__/ui/interaction/toast.test.ts
  packages/taro-h5/__tests__/ui/navigation.test.ts
  packages/taro-h5/jest.config.js
  packages/taro-h5/src/api/device/scan.ts
  packages/taro-h5/src/api/location/getLocation.ts
  packages/taro-h5/src/api/location/index.ts
  packages/taro-h5/src/api/utils/index.ts
Labels: A-api, T-h5

#11653 feat(h5): 增加vue3/tsx组件类型定义
  packages/taro-components/types/common.d.ts
  packages/taro-components/types/index.vue3.d.ts
  packages/taro-components/vue3.d.ts
Labels: A-typings

#11604 feat(h5): h5支持中文页面路径名称
  packages/taro-components/src/components/tabbar/tabbar.tsx
  packages/taro-router/src/router/spa.ts
Labels: A-router, P-2, T-h5

#11106 feat(h5): 支持 PickerView、PickerViewColumn 组件
  .stylelintignore
  .stylelintrc
  package.json
  packages/taro-components/__tests__/picker-view.spec.js
  packages/taro-components/__tests__/unimplemented.spec.js
  packages/taro-components/src/components/audio/style/index.scss
  packages/taro-components/src/components/button/style/index.scss
  packages/taro-components/src/components/canvas/canvas.tsx
  packages/taro-components/src/components/canvas/style/index.scss
  packages/taro-components/src/components/checkbox/style/index.scss
  packages/taro-components/src/components/image/style/index.scss
  packages/taro-components/src/components/input/index.scss
  packages/taro-components/src/components/navigator/navigator.tsx
  packages/taro-components/src/components/navigator/style/index.scss
  packages/taro-components/src/components/picker-view/picker-view-column.tsx
  packages/taro-components/src/components/picker-view/picker-view.tsx
  packages/taro-components/src/components/picker-view/style/column.scss
  packages/taro-components/src/components/picker-view/style/index.scss
  packages/taro-components/src/components/picker/style/index.scss
  packages/taro-components/src/components/pull-to-refresh/pull-to-refresh.tsx
  packages/taro-components/src/components/pull-to-refresh/style/index.scss
  packages/taro-components/src/components/scroll-view/scroll-view.tsx
  packages/taro-components/src/components/scroll-view/style/index.scss
  packages/taro-components/src/components/swiper/style/index.scss
  packages/taro-components/src/components/swiper/swiper.tsx
  packages/taro-components/src/components/switch/style/index.scss
  packages/taro-components/src/components/tabbar/style/index.scss
  packages/taro-components/src/components/text/style/index.scss
  packages/taro-components/src/components/textarea/style/index.scss
  packages/taro-components/src/components/video/style/index.scss
  packages/taro-components/src/components/view/style/index.scss
  packages/taro-components/src/components/web-view/style/index.scss
  packages/taro-components/src/utils/index.ts
  packages/taro-components/src/utils/style.ts
  packages/taro-components/src/utils/url.ts
  packages/taro-components/types/Input.d.ts
  packages/taro-components/types/PickerViewColumn.d.ts
  packages/taro-components/types/common.d.ts
  packages/taro-components/types/index.vue3.d.ts
  packages/taro-h5/__tests__/location/index.test.ts
  packages/taro-h5/src/api/location/getLocation.ts
  packages/taro-h5/src/api/utils/index.ts
  packages/taro/html.css
  packages/taro/html5.css
  yarn.lock
Labels: A-components, V-3, T-h5

#11666 fix: 修复showToast图标错误
  packages/taro-rn/src/lib/showModal/error.png
  packages/taro-rn/src/lib/showModal/toast.tsx
Labels: T-rn

#11672 fix(cli): 删除 CLI 冗余依赖，fix #11097
  package.json
  packages/taro-cli/package.json
  packages/taro-plugin-mini-ci/package.json
  packages/taro-plugin-mini-ci/src/AlipayCI.ts
  packages/taro-plugin-mini-ci/src/SwanCI.ts
  packages/taro-plugin-mini-ci/src/TTCI.ts
  packages/taro-plugin-mini-ci/types/AlipayCI.d.ts
  packages/taro-plugin-mini-ci/types/TTCI.d.ts
  yarn.lock
Labels: V-3

#11682 chore(eslint): 更新 eslint 插件的版本以兼容 eslint8
  packages/eslint-config-taro/package.json
  packages/taro-cli/templates/default/package.json.tmpl
  yarn.lock
Labels: V-3

#11542 feat(h5): 支持播放 hls 视频
  packages/taro-components/package.json
  packages/taro-components/src/components/video/utils.ts
  packages/taro-components/src/components/video/video-control.tsx
  packages/taro-components/src/components/video/video.tsx
  packages/taro-components/types/Video.d.ts
Labels: A-components, V-3, T-h5

#11705 fix(jsx-to-stylesheet): 修复 css module Object.assign 等 callExpression 问题
  packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/__tests__/index.spec.js
  packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/src/index.ts
Labels: T-rn

#11589 fix(mini-runner): 修复 @babel/parser 与 acron 关于动态 `import()` 解析类型不一致导致的报错
  packages/taro-mini-runner/src/plugins/TaroNormalModulesPlugin.ts
Labels: V-3

#11735 fix(rn): previewImage use modal
  packages/taro-rn/src/lib/previewImage/index.tsx
  yarn.lock
Labels: T-rn

#11709 Feat/line height 增加 line-height 合法值的 stylelint 检测
  packages/css-to-react-native/__tests__/index.spec.js
  packages/css-to-react-native/src/index.js
  packages/stylelint-config-taro-rn/__tests__/index.test.js
  packages/stylelint-config-taro-rn/index.js
  packages/stylelint-taro-rn/jest-setup.js
  packages/stylelint-taro-rn/src/rules/css-property-no-unknown/__tests__/index.js
  packages/stylelint-taro-rn/src/rules/index.js
  packages/stylelint-taro-rn/src/rules/line-height-no-value-without-unit/README.md
  packages/stylelint-taro-rn/src/rules/line-height-no-value-without-unit/__tests__/index.js
  packages/stylelint-taro-rn/src/rules/line-height-no-value-without-unit/index.js
  packages/stylelint-taro-rn/src/rules/style-property-no-unknown/__tests__/index.js
Labels: T-rn
