Repository NervJS/taro, pull requests merged in 2022-10, with the labels that each got.

#12605 feat: revert #4599, 并参照小程序抹平err时字段
  packages/taro-h5/__tests__/network/request.test.ts
  packages/taro-h5/src/api/network/request/index.ts
Labels: T-h5

#12559 fix(types): 类型同步优化 fix #12551
  .github/workflows/dependabot-update-lockfile.yml
  packages/taro-components/types/Button.d.ts
  packages/taro-components/types/Canvas.d.ts
  packages/taro-components/types/CoverImage.d.ts
  packages/taro-components/types/CoverView.d.ts
  packages/taro-components/types/Image.d.ts
  packages/taro-components/types/Input.d.ts
  packages/taro-components/types/Map.d.ts
  packages/taro-components/types/MovableView.d.ts
  packages/taro-components/types/NavigationBar.d.ts
  packages/taro-components/types/PickerView.d.ts
  packages/taro-components/types/ScrollView.d.ts
  packages/taro-components/types/Swiper.d.ts
  packages/taro-components/types/Switch.d.ts
  packages/taro-components/types/Textarea.d.ts
  packages/taro-components/types/Video.d.ts
  packages/taro-components/types/View.d.ts
  packages/taro-mini-runner/src/index.ts
  packages/taro-mini-runner/src/plugins/MiniPlugin.ts
  packages/taro-mini-runner/src/plugins/TaroNormalModulesPlugin.ts
  packages/taro-mini-runner/src/utils/types.ts
  packages/taro-webpack-runner/src/config/postcss.conf.ts
  packages/taro-webpack-runner/src/index.ts
  packages/taro-webpack5-runner/src/index.h5.ts
  packages/taro-webpack5-runner/src/plugins/MiniPlugin.ts
  packages/taro-webpack5-runner/src/plugins/TaroNormalModulesPlugin.ts
  packages/taro-webpack5-runner/src/postcss/postcss.h5.ts
  packages/taro-webpack5-runner/src/utils/types.ts
  packages/taro-webpack5-runner/src/webpack/H5WebpackModule.ts
  packages/taro/types/api/media/image.d.ts
  packages/taro/types/compile.d.ts
  packages/taro/types/compile/compiler.d.ts
  packages/taro/types/compile/config/h5.d.ts
  packages/taro/types/compile/config/index.d.ts
  packages/taro/types/compile/config/manifest.d.ts
  packages/taro/types/compile/config/mini.d.ts
  packages/taro/types/compile/config/project.d.ts
  packages/taro/types/compile/config/util.d.ts
  packages/taro/types/compile/hooks.d.ts
  packages/taro/types/compile/index.d.ts
  packages/taro/types/taro.component.d.ts
Labels: A-typings

#12614 fix: promisify tt.getUserProfile
  packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap
  packages/taro-tt/src/apis-list.ts
Labels: question, V-3

#12639 make react-native-svg optional
  packages/taro-components-rn/package.json
  packages/taro-components-rn/src/components/Image/index.tsx
  pnpm-lock.yaml
Labels: T-rn

#12669 fix(cli): 升级默认模板的 vue-loader 到最新版本，fix #12602
  packages/taro-cli/templates/default/package.json.tmpl
Labels: V-3

#12670 fix(webpack5): 修复 prerender 报错，fix #12622
  packages/shared/src/template.ts
  packages/taro-webpack5-runner/src/index.mini.ts
  packages/taro-webpack5-runner/src/prerender/prerender.ts
Labels: V-3

#12663 fix(tt): 支持PayButton、ConsumeCard组件，fix #12650
  packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap
  packages/taro-tt/src/components-react.ts
  packages/taro-tt/src/components.ts
Labels: V-3

#12662 fix(runtime): 修复tmpl_0_view not found 警告，fix #12558
  packages/taro-runtime/src/dsl/common.ts
Labels: V-3

#12675 fix(runner): 修复小程序插件编译报错，支持页面生命周期，fix #12603
  examples/build-weapp-plugin/package.json
  examples/build-weapp-plugin/yarn.lock
  packages/taro-mini-runner/src/plugins/MiniPlugin.ts
  packages/taro-plugin-react/src/runtime/connect-native.ts
  packages/taro-webpack5-runner/src/plugins/MiniPlugin.ts
Labels: V-3

#12583 fix(runtime): perf统计setData耗时不准确
  packages/taro-runtime/src/dom/root.ts
  packages/taro-runtime/src/perf.ts
Labels: A-runtime, V-3

#12627 feat(slot): 编译的原生组件支持使用 slot，fix #11865
  examples/blended-taro-component-vue3/miniapp/pages/index/index.json
  examples/blended-taro-component-vue3/miniapp/pages/index/index.wxml
  examples/blended-taro-component-vue3/taro-project/package.json
  examples/blended-taro-component-vue3/taro-project/src/app.config.ts
  examples/blended-taro-component-vue3/taro-project/src/components/article/index.config.ts
  examples/blended-taro-component-vue3/taro-project/src/components/article/index.vue
  examples/blended-taro-component-vue3/taro-project/yarn.lock
  examples/blended-taro-component/miniapp/pages/index/index.json
  examples/blended-taro-component/miniapp/pages/index/index.wxml
  examples/blended-taro-component/taro-project/package.json
  examples/blended-taro-component/taro-project/src/app.config.js
  examples/blended-taro-component/taro-project/src/components/article/index.config.js
  examples/blended-taro-component/taro-project/src/components/article/index.jsx
  examples/blended-taro-component/taro-project/src/components/picker/index.jsx
  examples/blended-taro-component/taro-project/yarn.lock
  packages/shared/src/components.ts
  packages/shared/src/template.ts
  packages/taro-components/mini/index.js
  packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/compiler-macros.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/jd.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap
Labels: V-3

#12600 chore: taro-transformer-wx 等 prettier 更新2.x以支持 singleAttributePerLine
  packages/css-to-react-native/package.json
  packages/stylelint-taro-rn/package.json
  packages/taro-cli/package.json
  packages/taro-transformer-wx/package.json
  packages/taroize/package.json
Labels: V-2

#12667 fix(mode): 优化 mode 判断方式 fix #12633
  packages/taro-components/stencil.config.ts
  packages/taro-h5/src/api/base/system.ts
  packages/taro-plugin-react/src/webpack.h5.ts
  packages/taro-plugin-react/src/webpack.mini.ts
  packages/taro-router/src/api.ts
  packages/taro-webpack5-prebundle/src/h5.ts
  packages/taro-webpack5-prebundle/src/index.ts
  packages/taro-webpack5-prebundle/src/mini.ts
  packages/taro-webpack5-prebundle/src/prebundle/index.ts
  packages/taro-webpack5-runner/src/index.h5.ts
  packages/taro-webpack5-runner/src/index.mini.ts
  packages/taro-webpack5-runner/src/webpack/Combination.ts
  packages/taro-webpack5-runner/src/webpack/H5WebpackModule.ts
  packages/taro-webpack5-runner/src/webpack/H5WebpackPlugin.ts
Labels: A-runner, V-3

#12678 chore(release): publish 3.5.7
  package.json
  packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/package.json
  packages/babel-plugin-transform-taroapi/package.json
  packages/babel-preset-taro/package.json
  packages/create-app/package.json
  packages/css-to-react-native/package.json
  packages/eslint-config-taro/package.json
  packages/postcss-html-transform/package.json
  packages/postcss-plugin-constparse/package.json
  packages/postcss-pxtransform/package.json
  packages/shared/package.json
  packages/stylelint-config-taro-rn/package.json
  packages/stylelint-taro-rn/package.json
  packages/taro-alipay/package.json
  packages/taro-api/package.json
  packages/taro-cli/package.json
  packages/taro-components-react/package.json
  packages/taro-components-rn/package.json
  packages/taro-components/package.json
  packages/taro-extend/package.json
  packages/taro-h5/package.json
  packages/taro-helper/package.json
  packages/taro-jd/package.json
  packages/taro-loader/package.json
  packages/taro-mini-runner/package.json
  packages/taro-plugin-html/package.json
  packages/taro-plugin-mini-ci/package.json
  packages/taro-plugin-react-devtools/package.json
  packages/taro-plugin-react/package.json
  packages/taro-plugin-vue-devtools/package.json
  packages/taro-plugin-vue2/package.json
  packages/taro-plugin-vue3/package.json
  packages/taro-qq/package.json
  packages/taro-react/package.json
  packages/taro-rn-runner/package.json
  packages/taro-rn-style-transformer/package.json
  packages/taro-rn-supporter/package.json
  packages/taro-rn-transformer/package.json
  packages/taro-rn/package.json
  packages/taro-router-rn/package.json
  packages/taro-router/package.json
  packages/taro-runner-utils/package.json
  packages/taro-runtime-rn/package.json
  packages/taro-runtime/package.json
  packages/taro-service/package.json
  packages/taro-swan/package.json
  packages/taro-tt/package.json
  packages/taro-weapp/package.json
  packages/taro-webpack-runner/package.json
  packages/taro-webpack5-prebundle/package.json
  packages/taro-webpack5-runner/package.json
  packages/taro-with-weapp/package.json
  packages/taro/package.json
  packages/taroize/package.json
Labels: V-3

#12437 feat(taro-plugin-mini-ci): Taro 小程序端构建CI（持续集成）插件重大更新
  packages/taro-cli/src/doctor/configSchema.ts
  packages/taro-plugin-mini-ci/README.md
  packages/taro-plugin-mini-ci/package.json
  packages/taro-plugin-mini-ci/src/AlipayCI.ts
  packages/taro-plugin-mini-ci/src/BaseCi.ts
  packages/taro-plugin-mini-ci/src/DingtalkCI.ts
  packages/taro-plugin-mini-ci/src/QRCode.ts
  packages/taro-plugin-mini-ci/src/SwanCI.ts
  packages/taro-plugin-mini-ci/src/TTCI.ts
  packages/taro-plugin-mini-ci/src/WeappCI.ts
  packages/taro-plugin-mini-ci/src/hooks.ts
  packages/taro-plugin-mini-ci/src/index.ts
  packages/taro-plugin-mini-ci/src/types.d.ts
  packages/taro-plugin-mini-ci/src/utils/compareVersion.ts
  packages/taro-plugin-mini-ci/src/utils/npm.ts
  packages/taro-plugin-mini-ci/src/utils/qrcode.ts
Labels: enhancement

#12497 New Feature: history api for using react(vue-)router in miniprogram
  packages/taro-mini-runner/src/webpack/build.conf.ts
  packages/taro-runtime/package.json
  packages/taro-runtime/src/bom/URLSearchParams.ts
  packages/taro-runtime/src/bom/history.ts
  packages/taro-runtime/src/bom/location.ts
  packages/taro-runtime/src/bom/window.ts
  packages/taro-runtime/src/constants/index.ts
  packages/taro-runtime/src/dsl/common.ts
  packages/taro-runtime/src/dsl/instance.ts
  packages/taro-runtime/src/index.ts
  packages/taro-runtime/src/utils/cache.ts
  packages/taro-webpack5-prebundle/src/mini.ts
  packages/taro-webpack5-prebundle/src/utils/index.ts
  packages/taro-webpack5-runner/src/webpack/MiniWebpackPlugin.ts
  pnpm-lock.yaml
Labels: enhancement

#12691 fix(types): service & view catchMove
  packages/taro-components/types/View.d.ts
  packages/taro-service/package.json
  packages/taro-service/src/Config.ts
  packages/taro-service/src/Kernel.ts
  packages/taro-service/src/Plugin.ts
  packages/taro-service/src/index.ts
  packages/taro-service/src/platform-plugin-base.ts
  packages/taro-service/src/utils/types.ts
  packages/taro-service/types/Config.d.ts
  packages/taro-service/types/Kernel.d.ts
  packages/taro-service/types/Plugin.d.ts
  packages/taro-service/types/index.d.ts
  packages/taro-service/types/platform-plugin-base.d.ts
Labels: A-typings

#12736 chore(cli): 移除 nerv 相关逻辑
  packages/taro-cli/src/doctor/packageValidator.ts
  packages/taro-cli/src/presets/commands/info.ts
  packages/taro-cli/src/presets/commands/update.ts
  packages/taro-helper/src/constants.ts
Labels: V-3

#12710 fix: win filename 兼容
  packages/taro-webpack-runner/src/util/chain.ts
Labels: question, V-3
