Repository NervJS/taro, pull requests merged in 2022-05, with the labels that each got.

#11545 feat(h5): Router解析出来的params供赋值给getCurrentInstance()?.router?.params
  packages/taro-loader/src/h5.ts
  packages/taro-router/src/router/spa.ts
  packages/taro-runtime/src/dsl/instance.ts
  packages/taro/types/taro.component.d.ts
Labels: A-router, V-3, T-h5

#11744 fix(h5): stencil slot 与 react render冲突问题 #11379
  packages/taro-components/src/components/view/view.tsx
Labels: T-h5

#11747 fix: 跳转进入到可下拉刷新的页面无法下拉刷新
  packages/taro-components/src/components/pull-to-refresh/pull-to-refresh.tsx
Labels: T-h5

#11782 fix(helper): 修复配置文件 import json 文件报错的问题，fix #11295
  packages/taro-helper/src/utils.ts
Labels: V-3

#11777 feat(harmony-api): 完成节点api。目前select只支持id、class选择器
  packages/taro-harmony/src/apis/apis.ts
  packages/taro-harmony/src/apis/wxml/index.ts
  packages/taro-harmony/src/apis/wxml/nodesRef.ts
  packages/taro-harmony/src/apis/wxml/selectorQuery.ts
Labels: T-harmony

#11827 fix(runtime): 调整路由参数逻辑, fix #11713
  packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/bytedance.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/compiler-macros.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/jd.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap
  packages/taro-plugin-react/src/runtime/connect-native.ts
  packages/taro-runtime/src/current.ts
  packages/taro-runtime/src/dsl/common.ts
  packages/taro-runtime/src/next-tick.ts
Labels: V-3

#11831 fix(runtime): 支持 style 设置部分 webkit 样式，fix #8109 #11802
  packages/taro-runtime/src/dom/style.ts
  packages/taro-runtime/src/dom/style_properties.ts
Labels: V-3

#11830 feat(shared): 支持为第三方自定义组件的属性设置默认值，fix #11575
  packages/shared/src/template.ts
Labels: V-3
