Repository NervJS/taro, pull requests merged in 2022-03, with the labels that each got.

#11344 feat(rn): react navigation packages upgrade
  packages/taro-rn-transformer/src/app.ts
  packages/taro-rn/package.json
  packages/taro-rn/src/lib/showModal/toast.tsx
  packages/taro-rn/src/types/definition.d.ts
  packages/taro-rn/tsconfig.json
  packages/taro-router-rn/package.json
  packages/taro-router-rn/src/navigationBar.ts
  packages/taro-router-rn/src/provider.ts
  packages/taro-router-rn/src/rootNavigation.ts
  packages/taro-router-rn/src/router.tsx
  packages/taro-router-rn/src/utils/index.ts
  packages/taro-router-rn/src/view/BackButton.tsx
  packages/taro-router-rn/src/view/Badge.tsx
  packages/taro-router-rn/src/view/HeadTitle.tsx
  packages/taro-router-rn/src/view/Loading.tsx
  packages/taro-router-rn/src/view/TabBar.tsx
  packages/taro-router-rn/src/view/TabBarItem.tsx
  yarn.lock
Labels: V-3, T-rn

#11316 修复 preact eslint
  packages/eslint-config-taro/package.json
Labels: V-3

#11433 fix(h5): query 不进行 decode
  packages/taro-router/src/router/page.ts
Labels: T-h5

#11257 Fix/doctor/krystal
  packages/eslint-config-taro/index.js
  packages/taro-cli/src/doctor/packageValidator.ts
  packages/taro-helper/src/constants.ts
Labels: A-cli, V-3

#11436 feat(vue3): 支持vue3类组件
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap
  packages/taro-plugin-vue3/src/runtime/connect.ts
Labels: V-3

#11459 fix(rn): image in form bug
  packages/taro-components-rn/src/components/Form/index.tsx
Labels: T-rn

#11501 fix(rn): form value resetted
  packages/taro-components-rn/src/components/Form/index.tsx
Labels: T-rn

#11441 fix(mini-runner): 修复使用原生写法的自定义 Tabbar 失败的问题，fix #11437
  examples/custom-tabbar-react/package.json
  examples/custom-tabbar-react/yarn.lock
  examples/custom-tabbar-vue3/package.json
  examples/custom-tabbar-vue3/yarn.lock
  packages/taro-mini-runner/src/plugins/MiniPlugin.ts
Labels: V-3

#11505 fix(rn): 修复 request 对 header content-type 的处理，fix https://github.com/NervJS/taro/issues/11502
  packages/taro-rn/src/__tests__/request.test.js
  packages/taro-rn/src/lib/request/index.ts
Labels: T-rn

#11440 fix(vue3): 使用 setup 语法编写 vue3 内置组件，fix #11393
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap
  packages/taro-plugin-vue3/src/runtime/connect.ts
Labels: V-3

#11523 fix(vue3): 修复 Vue3 使用原生组件时事件触发失败的问题，#9794
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap
  packages/taro-plugin-vue3/src/runtime/connect.ts
Labels: V-3

#11528 feat(weapp): 新增对 ShareElement 组件的支持，fix #11466
  packages/taro-components/types/PageContainer.d.ts
  packages/taro-components/types/ShareElement.d.ts
  packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/compiler-macros.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap
  packages/taro-weapp/src/components-react.ts
  packages/taro-weapp/src/components.ts
  packages/taro-weapp/src/template.ts
Labels: V-3

#11529 fix(shared): 让 Slot 组件支持设置 style，fix #11495
  packages/shared/src/template.ts
Labels: V-3

#11531 feat(weapp): 让 Input 支持 KeyboardAccessory，fix #11510
  packages/taro-weapp/src/program.ts
  packages/taro-weapp/src/template.ts
Labels: V-3

#11539 fix: react-native-screens version
  packages/taro-router-rn/package.json
  yarn.lock
Labels: T-rn

#11432 feat: change h5 request to taro-h5
  packages/taro-h5/src/api/network/request/index.ts
Labels: T-h5
