Repository NervJS/taro, pull requests merged in 2022-12, with the labels that each got.

#12859 fix(alipay): standardize subPackages and tabBar.customize in appConfig
  packages/taro-alipay/src/program.ts
Labels: T-alipay

#12906 fix(h5)：Taro.showActionSheet在第二次打开时，点击取消没有回调
  packages/taro-h5/src/api/ui/interaction/actionSheet.ts
Labels: A-api, V-3, T-h5

#12930 feat(types): 增加百度小程序激励视频广告 API 的类型
  packages/taro/types/api/ad/index.d.ts
Labels: V-3

#12939 fix(prebundle): 预编译排除继承 copyPlugin 和babel-loader，fix #12839
  packages/taro-webpack5-prebundle/src/prebundle/index.ts
Labels: V-3

#12951 fix(webpack5): 自动分析小程序模板里依赖的wxs文件，fix #9055
  packages/taro-webpack5-runner/src/loaders/miniTemplateLoader.ts
  packages/taro-webpack5-runner/src/loaders/miniXScriptLoader.ts
  packages/taro-webpack5-runner/src/webpack/MiniWebpackModule.ts
  packages/taro-webpack5-runner/src/webpack/WebpackModule.ts
Labels: V-3

#12963 fix(rn): uploadFile file response
  packages/taro-rn/src/lib/file.ts
Labels: T-rn

#12959 fix: #12958
  packages/taro-components-rn/package.json
  pnpm-lock.yaml
Labels: T-rn

#12857 修复部分android机型点击命中率低
  packages/taro-components-rn/src/components/ClickableSimplified/index.tsx
Labels: T-rn

#12862 修复多行文本在单行时,无法设置低于35的高度
  packages/taro-components-rn/src/components/Input/index.tsx
Labels: T-rn

#13002 fix(types): 修复钩子缺少的入参 fix #12983
  packages/taro/types/taro.hooks.d.ts
Labels: A-typings

#13029 fix(react): prebundle 排除 mobx 相关依赖
  packages/taro-plugin-react/src/index.ts
Labels: V-3

#13022 fix(vue3): 修复 v-html 缺失组件模板的问题，#12973
  packages/taro-plugin-vue3/src/webpack.mini.ts
Labels: V-3

#13013 fix(runtime): 修复独立分包模板报错的问题，fix #12995
  .gitignore
  examples/weapp-independent-subpackages/package.json
  examples/weapp-independent-subpackages/yarn.lock
  packages/taro-cli/templates/default/_gitignore
  packages/taro-runtime/src/dsl/common.ts
Labels: V-3

#13012 fix(prebundle): 修复装饰器语法报错的问题，fix #13007
  packages/taro-webpack5-prebundle/src/utils/constant.ts
Labels: V-3

#13011 Fix/alipay ble
  packages/taro-alipay/src/apis.ts
  packages/taro-mini-runner/src/__tests__/__snapshots__/alipay.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap
Labels: V-3

#13054 fix(components): 修复 swiper 在 circular 模式下自动播放故障
  packages/taro-components/src/components/swiper/swiper.tsx
Labels: A-components, V-3, T-h5

#13045 fix(template): 新增类型导出适配 vue 开发插件
  packages/taro-cli/templates/default/types/global.d.ts
Labels: A-typings
