Repository NervJS/taro, pull requests merged in 2022-07, with the labels that each got.

#12039 fix(components): 优化 swiper 样式引入 fix #12034
  packages/taro-components/src/components/swiper/style/index.scss
  packages/taro-components/src/components/swiper/style/swiper.min.css
Labels: A-components, P-1, T-h5

#11517 feat(mini-runner): 支持用户对内置配置进行修改
  packages/taro-mini-runner/src/index.ts
Labels: V-2

#10934 chore: 升级mini-css-extract-plugin插件至^0.8.0,接收ignoreOrder参数
  packages/taro-mini-runner/package.json
  packages/taro-mini-runner/yarn.lock
  packages/taro-rn-runner/package.json
  packages/taro-rn-runner/yarn.lock
  packages/taro-webpack-runner/package.json
  packages/taro-webpack-runner/yarn.lock
Labels: V-2

#12091 fix(h5): devserver publicPath error
  packages/taro-webpack5-prebundle/src/h5.ts
  packages/taro-webpack5-runner/src/index.h5.ts
Labels: T-h5

#11861 feat(cli)/create app (支持 create 创建项目)
  packages/create-app/.eslintrc.js
  packages/create-app/README.md
  packages/create-app/package.json
  packages/create-app/src/createApp.ts
  packages/create-app/src/index.ts
  packages/create-app/src/util/index.ts
  packages/create-app/tsconfig.json
Labels: V-3

#12117 fix: fileType为jpg时，表现不符合预期
  .github/workflows/nodejs.yml
  packages/taro-h5/src/api/canvas/canvasToTempFilePath.ts
Labels: T-h5

#12147 feat(taro-runtime-rn): implement useReady hook in taro-rn
  packages/taro-rn/src/api/index.ts
  packages/taro-runtime-rn/src/hooks.ts
  packages/taro-runtime-rn/src/page.ts
  packages/taro-runtime-rn/src/types/index.d.ts
Labels: V-3, T-rn

#12150 fix(rn-style-transformer): 解决 scss nest importer 不执行问题
  packages/taro-rn-style-transformer/__tests__/platform.spec.js
  packages/taro-rn-style-transformer/package.json
  packages/taro-rn-style-transformer/src/transforms/sass.ts
  pnpm-lock.yaml
Labels: T-rn
