Repository NervJS/taro, pull requests merged in 2022-09, with the labels that each got.

#12425 feat: update auto install expo version
  packages/taro-cli/src/presets/platforms/rn.ts
Labels: V-3, T-rn

#12362 fix(prebundle): 优化 vue3 与 prebundle 结合
  .github/workflows/dependabot-update-lockfile.yml
  packages/taro-components/h5/react/components/index.js
  packages/taro-components/types/Map.d.ts
  packages/taro-components/types/RootPortal.d.ts
  packages/taro-components/types/Video.d.ts
  packages/taro-components/types/index.vue3.d.ts
  packages/taro-plugin-vue2/src/index.ts
  packages/taro-plugin-vue3/src/index.ts
  packages/taro-webpack5-prebundle/src/h5.ts
Labels: A-runner

#12438 fix(taro-rn): 修复 showActionSheet rn android 端与其他端不一致的问题
  packages/taro-rn/src/lib/showActionSheet/ActionSheet.tsx
Labels: T-rn

#12461 fix(weapp): createOffscreenCanvas方法接收初始化的参数 (#12391)
  packages/taro/types/api/canvas/index.d.ts
Labels: A-typings

#12460 fix(postcss): pxtransform baseFontSize 取值问题
  packages/postcss-pxtransform/__tests__/index.test.js
  packages/postcss-pxtransform/index.js
  packages/taro-webpack-runner/src/util/index.ts
  packages/taro-webpack5-runner/src/webpack/H5WebpackPlugin.ts
Labels: A-runner, T-h5

#12469 fix(taro-components): 修复 input type=number maxlength=-1 情况下,内容无法输入问题
  packages/taro-components/src/components/input/input.tsx
Labels: A-components, T-h5

#12459 build(taro-components): 添加 H5 组件 stencil 构建 sourceMap 配置
  packages/taro-components/package.json
  packages/taro-components/stencil.config.ts
  packages/taro-components/tsconfig.json
Labels: A-components, T-h5

#12466 fix(component-rn): Input TextArea 解决 focus 变更,聚焦失焦不同步
  packages/taro-components-rn/src/components/Input/PropsType.tsx
  packages/taro-components-rn/src/components/Input/index.tsx
  packages/taro-components-rn/src/components/Textarea/index.tsx
  packages/taro-components-rn/src/utils/index.ts
Labels: T-rn

#12423 fix(video): 捕获hls.js中的错误信息
  packages/taro-components/src/components/video/video.tsx
Labels: T-h5

#12478 fix(jsx-to-stylesheet): 引入同名 style 文件时变量名冲突
  packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/__tests__/__snapshots__/index.spec.js.snap
  packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/__tests__/index.spec.js
  packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/src/index.ts
Labels: T-rn

#12441 refactor(types): 根据各个小程序官方文档，同步组件类型声明
  packages/taro-components-rn/src/components/Radio/PropsType.tsx
  packages/taro-components-rn/src/components/Video/index.tsx
  packages/taro-components/package.json
  packages/taro-components/src/utils/json-schema-to-types.ts
  packages/taro-components/types/Ad.d.ts
  packages/taro-components/types/AdCustom.d.ts
  packages/taro-components/types/Audio.d.ts
  packages/taro-components/types/Block.d.ts
  packages/taro-components/types/Button.d.ts
  packages/taro-components/types/Camera.d.ts
  packages/taro-components/types/Canvas.d.ts
  packages/taro-components/types/Checkbox.d.ts
  packages/taro-components/types/CheckboxGroup.d.ts
  packages/taro-components/types/CoverImage.d.ts
  packages/taro-components/types/CoverView.d.ts
  packages/taro-components/types/Editor.d.ts
  packages/taro-components/types/Form.d.ts
  packages/taro-components/types/FunctionalPageNavigator.d.ts
  packages/taro-components/types/Icon.d.ts
  packages/taro-components/types/Image.d.ts
  packages/taro-components/types/Input.d.ts
  packages/taro-components/types/Label.d.ts
  packages/taro-components/types/LivePlayer.d.ts
  packages/taro-components/types/LivePusher.d.ts
  packages/taro-components/types/Map.d.ts
  packages/taro-components/types/MatchMedia.d.ts
  packages/taro-components/types/MovableArea.d.ts
  packages/taro-components/types/MovableView.d.ts
  packages/taro-components/types/NavigationBar.d.ts
  packages/taro-components/types/Navigator.d.ts
  packages/taro-components/types/OfficialAccount.d.ts
  packages/taro-components/types/OpenData.d.ts
  packages/taro-components/types/PageContainer.d.ts
  packages/taro-components/types/PageMeta.d.ts
  packages/taro-components/types/Picker.d.ts
  packages/taro-components/types/PickerView.d.ts
  packages/taro-components/types/PickerViewColumn.d.ts
  packages/taro-components/types/Progress.d.ts
  packages/taro-components/types/Radio.d.ts
  packages/taro-components/types/RadioGroup.d.ts
  packages/taro-components/types/RichText.d.ts
  packages/taro-components/types/ScrollView.d.ts
  packages/taro-components/types/ShareElement.d.ts
  packages/taro-components/types/Slider.d.ts
  packages/taro-components/types/Swiper.d.ts
  packages/taro-components/types/SwiperItem.d.ts
  packages/taro-components/types/Switch.d.ts
  packages/taro-components/types/Text.d.ts
  packages/taro-components/types/Textarea.d.ts
  packages/taro-components/types/Video.d.ts
  packages/taro-components/types/View.d.ts
  packages/taro-components/types/VoipRoom.d.ts
  packages/taro-components/types/WebView.d.ts
  pnpm-lock.yaml
Labels: A-typings

#12498 fix(types): 修复类型及属性名错误的问题
  packages/taro-components/package.json
  packages/taro-components/types/Canvas.d.ts
  packages/taro-components/types/Input.d.ts
  packages/taro-components/types/Progress.d.ts
  packages/taro-components/types/Video.d.ts
  pnpm-lock.yaml
Labels: A-typings

#12494 fix(types): 修复部分类型自动同步错误
  packages/taro-components/types/Ad.d.ts
  packages/taro-components/types/AdCustom.d.ts
  packages/taro-components/types/Button.d.ts
  packages/taro-components/types/CheckboxGroup.d.ts
  packages/taro-components/types/CoverView.d.ts
  packages/taro-components/types/Editor.d.ts
  packages/taro-components/types/Form.d.ts
  packages/taro-components/types/Input.d.ts
  packages/taro-components/types/LivePusher.d.ts
  packages/taro-components/types/Map.d.ts
  packages/taro-components/types/MovableView.d.ts
  packages/taro-components/types/PageContainer.d.ts
  packages/taro-components/types/PageMeta.d.ts
  packages/taro-components/types/Picker.d.ts
  packages/taro-components/types/Radio.d.ts
  packages/taro-components/types/RichText.d.ts
  packages/taro-components/types/ScrollView.d.ts
  packages/taro-components/types/Swiper.d.ts
  packages/taro-components/types/Textarea.d.ts
  packages/taro-components/types/Video.d.ts
  packages/taro-components/types/View.d.ts
  packages/taro-components/types/VoipRoom.d.ts
  packages/taro-components/types/common.d.ts
  packages/taro/types/api/location/index.d.ts
  packages/taro/types/api/share/index.d.ts
Labels: A-typings

#12476 fix(taro-components): 优化 input 组件 type 为 number 或 digit 时,输入特殊符号导致交互异常问题
  packages/taro-components/src/components/input/input.tsx
Labels: A-components, T-h5

#12493 style: 支持较新版本的autoprefixer(7.0.0+)
  packages/taro/html5.css
Labels: V-3

#12501 feat: webpack-sources 的功能从webpack引入,避免执行引入版本有关问题
  package.json
  packages/taro-webpack5-prebundle/package.json
  packages/taro-webpack5-prebundle/src/utils/webpack.ts
  packages/taro-webpack5-prebundle/src/webpack/TaroContainerEntryModule.ts
  packages/taro-webpack5-prebundle/src/webpack/TaroContainerReferencePlugin.ts
  packages/taro-webpack5-runner/package.json
  packages/taro-webpack5-runner/src/plugins/MiniPlugin.ts
  packages/taro-webpack5-runner/src/plugins/MiniSplitChunksPlugin.ts
  packages/taro-webpack5-runner/src/plugins/TaroLoadChunksPlugin.ts
  packages/taro-webpack5-runner/src/utils/webpack.ts
  pnpm-lock.yaml
  types/webpack-sources.d.ts
Labels: A-runner, V-3, T-weapp, T-h5

#12502 chore: remove lint stage git add
  package.json
Labels: V-3

#12523 fix(prebundle): 修复预编译导致 vue devtools 报错的问题，fix #12452
  packages/taro-webpack5-prebundle/src/mini.ts
Labels: V-3

#12515 fix: taro convert error on 3.5.x
  packages/taro-cli/src/convertor/index.ts
Labels: V-3

#12535 fix(runner): 修复自定义环境变量导致的 mode 错误 fix #12436
  packages/taro-webpack5-runner/src/utils/types.ts
  packages/taro-webpack5-runner/src/webpack/Combination.ts
Labels: A-runner

#12429 Fix/h5/movable
  packages/taro-components/src/components/movable-area/movable-view.tsx
  packages/taro-components/types/MovableView.d.ts
Labels: T-h5
