Repository NervJS/taro, pull requests merged in 2022-08, with the labels that each got.

#12197 fix: isEntryFile path error on windows
  packages/taro-rn-supporter/src/taroTransformer.ts
Labels: T-rn

#12173 feat(taro-runtime-rn): implement useUnload hook in taro-rn
  packages/taro-rn/src/api/index.ts
  packages/taro-runtime-rn/src/hooks.ts
  packages/taro-runtime-rn/src/page.ts
  packages/taro-runtime-rn/src/types/index.d.ts
Labels: T-rn

#12177 feat(taro-runtime-rn): implement useLoad hook in taro-rn
  packages/taro-rn/src/api/index.ts
  packages/taro-runtime-rn/src/hooks.ts
  packages/taro-runtime-rn/src/page.ts
  packages/taro-runtime-rn/src/types/index.d.ts
Labels: T-rn

#12212 feat(rn-runner/rn-style): rollupTransform 参数格式化,解决参数丢失问题 && 调整类型声明文件
  packages/taro-rn-runner/src/config/build-component.ts
  packages/taro-rn-style-transformer/__tests__/config.spec.js
  packages/taro-rn-style-transformer/__tests__/index.spec.js
  packages/taro-rn-style-transformer/__tests__/platform.spec.js
  packages/taro-rn-style-transformer/src/index.ts
  packages/taro-rn-style-transformer/src/transforms/index.ts
  packages/taro-rn-style-transformer/src/transforms/less.ts
  packages/taro-rn-style-transformer/src/transforms/postcss.ts
  packages/taro-rn-style-transformer/src/transforms/sass.ts
  packages/taro-rn-style-transformer/src/transforms/stylus.ts
  packages/taro-rn-style-transformer/src/types/index.ts
  packages/taro-rn-style-transformer/src/utils/index.ts
  packages/taro-rn-style-transformer/src/utils/lessImport.ts
Labels: T-rn

#12203 fix(postcss): pxtransform 语法优化
  packages/postcss-pxtransform/index.js
  packages/taro-webpack-runner/src/util/index.ts
  packages/taro-webpack5-runner/src/webpack/H5WebpackPlugin.ts
Labels: T-h5

#12188 fix(types): udpate props fix #12180
  packages/taro-components/types/props.d.ts
Labels: A-typings

#12232 fix(taro-runtime-rn): register hooks in current instance instead of Page Component
  packages/taro-runtime-rn/src/instance.ts
  packages/taro-runtime-rn/src/page.ts
Labels: T-rn

#12257 fix: scancode safe area
  packages/taro-rn/src/__tests__/__snapshots__/scanCode.test.tsx.snap
  packages/taro-rn/src/lib/scanCode/index.tsx
  packages/taro-router-rn/src/view/TabBar.tsx
Labels: T-rn

#12280 fix(taro-runtime-rn): 修复rn 函数式组件中hook多实例触发问题
  packages/taro-runtime-rn/src/page.ts
  packages/taro-runtime-rn/src/utils.ts
Labels: T-rn

#12313 feat: use big qr in windows
  packages/taro-rn-runner/src/config/preview.ts
  packages/taro-rn-runner/src/index.ts
  packages/taro-rn-runner/src/utils.ts
Labels: V-3, T-rn

#12335 PickerComponent add itemStyle and indicatorStyle
  packages/taro-components-rn/src/components/Picker/multiSelector.tsx
  packages/taro-components-rn/src/components/Picker/selector.tsx
  packages/taro-components/types/Picker.d.ts
Labels: T-rn

#12248 fix(taro-webpack5-runner): enableSourceMap
  packages/taro-webpack5-runner/src/webpack/Combination.ts
Labels: question, V-3

#12344 fix(components): fix h5 oninput not trigger bug when ios autocorrect.…
  packages/taro-components/src/components/input/input.tsx
Labels: T-h5

#12339 fix: 页面为函数式组件时不再额外包裹 View #12305
  packages/taro-runtime-rn/src/page.ts
Labels: V-3, T-rn

#12285 fix(runner): remove duplicate id of native components
  packages/taro-mini-runner/src/plugins/TaroNormalModulesPlugin.ts
  packages/taro-webpack5-runner/src/plugins/TaroNormalModulesPlugin.ts
Labels: question

#12363 feat(weapp): 补充 openBusinessView 的类型定义
  packages/taro-h5/src/api/navigate/index.ts
  packages/taro/types/api/navigate/index.d.ts
Labels: A-typings

#12371 fix: tabbar paddingbottom error
  packages/taro-router-rn/src/view/TabBar.tsx
Labels: T-rn

#12378 fix: 修复 RN 样式 warning
  packages/css-to-react-native/__tests__/index.spec.js
  packages/css-to-react-native/src/css-to-react-native/transforms/border.js
Labels: T-rn

#12375 fix(textarea): 修复textarea组件高度设置无法生效的问题
  packages/taro-components/src/components/textarea/style/index.scss
Labels: T-h5

#12365 feat(jsx-to-rn-stylesheet): 当开启 cssModule 时，支持在 className 中设置多个值
  packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/__tests__/__snapshots__/index.spec.js.snap
  packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/__tests__/index.spec.js
  packages/babel-plugin-transform-react-jsx-to-rn-stylesheet/src/index.ts
Labels: V-3, T-rn
