Repository NervJS/taro, pull requests merged in 2022-11, with the labels that each got.

#12525 Feat/3.6 postcss8
  package.json
  packages/postcss-html-transform/package.json
  packages/postcss-html-transform/src/index.ts
  packages/postcss-plugin-constparse/index.js
  packages/postcss-plugin-constparse/package.json
  packages/postcss-pxtransform/index.js
  packages/postcss-pxtransform/package.json
  packages/taro-cli/package.json
  packages/taro-cli/src/convertor/index.ts
  packages/taro-cli/templates/default/package.json.tmpl
  packages/taro-helper/src/constants.ts
  packages/taro-mini-runner/package.json
  packages/taro-rn-style-transformer/package.json
  packages/taro-rn-style-transformer/src/transforms/postcss.ts
  packages/taro-rn-style-transformer/src/utils/reporterSkip.ts
  packages/taro-webpack-runner/package.json
  packages/taro-webpack5-runner/package.json
  pnpm-lock.yaml
Labels: enhancement

#12209 feat(runner): 独立分包添加公共逻辑抽取
  packages/taro-mini-runner/src/plugins/MiniPlugin.ts
  packages/taro-webpack5-runner/src/plugins/MiniPlugin.ts
Labels: V-3

#12698 fix(plugin-html): 修复开启html转译插件后，部分元素属性没有进行映射导致更新失败的问题
  packages/taro-plugin-html/src/runtime.ts
Labels: question

#12738 fix(h5): 补充 API 抛出事件遗漏的参数
  packages/taro-h5/src/utils/index.ts
Labels: A-api, T-h5

#12801 fix(components): button disable catch fix #12797
  packages/taro-components/src/components/button/button.tsx
Labels: A-components, T-h5
