Repository NervJS/taro, pull requests merged in 2023-01, with the labels that each got.

#13099 fix(types): 优化 vue 类型补充 fix #13081
  packages/taro-cli/templates/default/template_creator.js
  packages/taro-cli/templates/default/types/global.d.ts
  packages/taro-cli/templates/default/types/vue.d.ts
Labels: A-typings

#13079 fix(components): update swiper-item for circular
  packages/taro-components/src/components/swiper/swiper-item.tsx
Labels: A-components, T-h5

#13133 fix(taro-helper): 修复readConfig时,createSwcRegister没有对软链接的.config.js进行编译,导致Unexpected token 'export'
  packages/taro-helper/src/utils.ts
Labels: V-3

#13118 fix(runner): 修复独立分包下, 产物未引用公共 common 文件
  packages/taro-mini-runner/src/plugins/MiniPlugin.ts
  packages/taro-webpack5-runner/src/plugins/MiniPlugin.ts
Labels: V-3

#13052 feat: form组件百度小程序支持传入 skipSubscribeAuthorize 属性
  packages/taro-components/types/Form.d.ts
  packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap
  packages/taro-swan/src/components.ts
Labels: V-3

#13153 fix(runtime): 修复 onReady 偶现不触发的问题，fix #12424
  packages/taro-runtime/src/dsl/common.ts
Labels: V-3
