Repository NervJS/taro, pull requests merged in 2023-03, with the labels that each got.

#13303 chore(type): useShareAppMessage 类型定义增强
  packages/taro/types/taro.lifecycle.d.ts
Labels: A-typings

#13405 fix: move expo-modules-core to dev
  packages/taro-rn/package.json
  packages/taro-rn/src/lib/getAppBaseInfo/index.ts
  packages/taro-rn/src/lib/getUserProfile/index.ts
  packages/taro-rn/src/lib/index.ts
  packages/taro-rn/src/lib/unsupportedApi.ts
  pnpm-lock.yaml
Labels: V-3, T-rn

#13424 chore: 调整 prebundle 类型
  packages/taro-webpack5-prebundle/src/prebundle/index.ts
  packages/taro/types/compile/compiler.d.ts
Labels: V-3

#13400 feat(types): 补全组件支持标注
  packages/taro-components-advanced/src/components/virtual-list/react/list.ts
Labels: A-typings

#13420 chore(deps): 更新部分包 node-externals 依赖版本
  package.json
  packages/shared/package.json
  packages/taro-alipay/package.json
  packages/taro-api/package.json
  packages/taro-components-advanced/package.json
  packages/taro-components-advanced/rollup.config.js
  packages/taro-components-library-react/package.json
  packages/taro-components-library-react/rollup.config.js
  packages/taro-components-library-vue2/package.json
  packages/taro-components-library-vue2/rollup.config.js
  packages/taro-components-library-vue3/package.json
  packages/taro-components-library-vue3/rollup.config.js
  packages/taro-components-react/package.json
  packages/taro-components-react/rollup.config.js
  packages/taro-h5/package.json
  packages/taro-jd/package.json
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap
  packages/taro-platform-h5/package.json
  packages/taro-platform-h5/rollup.config.js
  packages/taro-plugin-html/package.json
  packages/taro-plugin-html/rollup.config.js
  packages/taro-plugin-http/package.json
  packages/taro-plugin-inject/package.json
  packages/taro-plugin-react-devtools/package.json
  packages/taro-plugin-react/package.json
  packages/taro-plugin-vue-devtools/package.json
  packages/taro-plugin-vue2/package.json
  packages/taro-plugin-vue3/package.json
  packages/taro-qq/package.json
  packages/taro-react/package.json
  packages/taro-router/package.json
  packages/taro-runtime/package.json
  packages/taro-swan/package.json
  packages/taro-tt/package.json
  packages/taro-weapp/package.json
  packages/taro-webpack-runner/src/__tests__/__snapshots__/vue.spec.ts.snap
  packages/taro-webpack-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap
  packages/taro-with-weapp/package.json
  pnpm-lock.yaml
Labels: dependencies

#13440 fix: 修复Taro.createInnerAudioContext执行destroy异常的问题
  packages/taro-h5/src/api/audio/index.js
Labels: V-2

#13401 feat(h5): 支持 textarea 组件 focus 属性
  packages/taro-components/src/components/input/input.tsx
  packages/taro-components/src/components/picker/picker.tsx
  packages/taro-components/src/components/textarea/readme.md
  packages/taro-components/src/components/textarea/textarea.tsx
  packages/taro-components/src/components/video/video.tsx
  packages/taro-components/types/Textarea.d.ts
Labels: A-components, T-h5

#13512 fix(h5): 优化 prebundle runtime 注入问题 fix #13450
  packages/taro-webpack5-prebundle/src/prebundle/index.ts
  packages/taro-webpack5-prebundle/src/webpack/TaroContainerPlugin.ts
  packages/taro-webpack5-prebundle/src/webpack/TaroContainerReferencePlugin.ts
  packages/taro-webpack5-runner/src/plugins/BuildNativePlugin.ts
  packages/taro-webpack5-runner/src/plugins/MiniPlugin.ts
  packages/taro-webpack5-runner/src/plugins/MiniSplitChunksPlugin.ts
Labels: A-PreBundle

#13536 fix(swan): 修复百度小程序 Text 组件嵌套不显示的问题，fix #13511
  packages/taro-mini-runner/src/__tests__/__snapshots__/swan.spec.ts.snap
  packages/taro-swan/src/index.ts
  packages/taro-swan/src/program.ts
  packages/taro-swan/src/template.ts
Labels: V-3

#13535 fix(request): onChunkReceived Callback 结构体错误
  packages/taro/types/api/network/request.d.ts
Labels: question, A-typings

#13508 feat(h5): 启用虚拟模块缓存
  packages/taro-loader/src/h5.ts
  packages/taro-webpack5-prebundle/package.json
  pnpm-lock.yaml
Labels: T-h5, A-PreBundle
