Repository NervJS/taro, pull requests merged in 2023-05, with the labels that each got.

#13766 fix: 从普通页面返回 tabbar 页面时展示动画
  packages/taro-router/src/router/page.ts
  packages/taro-router/src/router/spa.ts
Labels: A-router, T-h5

#13778 fix(textarea): 修改 showCount、controlled 类型定义
  packages/taro-components/types/Textarea.d.ts
Labels: A-typings, T-alipay

#13802 fix(webpack5): 修复 app 样式引用 common 样式的语法问题
  packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap
  packages/taro-mini-runner/src/plugins/MiniPlugin.ts
  packages/taro-webpack5-runner/src/__tests__/__snapshots__/mini-split-chunks.spec.ts.snap
  packages/taro-webpack5-runner/src/plugins/MiniPlugin.ts
Labels: V-3

#13841 fix(h5): InnerAudioContext 暂停后再播放没有继上次进度播放
  packages/taro-h5/src/api/media/audio/InnerAudioContext.ts
Labels: T-h5

#13834 fix(h5): 修改Taro.request传入array类型数据序列化问题
  packages/taro-h5/src/api/network/request/index.ts
Labels: T-h5

#13842 fix(h5): 修复 win 下开启 multi router 后页面不显示的问题 fix #13134
  packages/taro-loader/src/h5.ts
  packages/taro-webpack-runner/src/plugins/H5Plugin.ts
  packages/taro-webpack5-runner/src/plugins/H5Plugin.ts
Labels: A-router, T-h5

#13768 fix(runner): 优化外部模块设置 fix #13767
  packages/taro-helper/src/esbuild/utils.ts
Labels: A-runner

#13772 chore: 2.x的node-sass换成sass
  package.json
  packages/css-to-react-native/yarn.lock
  packages/stylelint-taro-rn/yarn.lock
  packages/taro-async-await/yarn.lock
  packages/taro-cli/yarn.lock
  packages/taro-components/package.json
  packages/taro-components/yarn.lock
  packages/taro-plugin-sass/package.json
  packages/taro-plugin-sass/src/index.ts
  packages/taro-plugin-sass/yarn.lock
  packages/taro-transformer-wx/yarn.lock
  packages/taroize/yarn.lock
  yarn.lock
Labels: V-2

#13897 feat(weapp): live-player 增加投屏接口
  packages/taro/types/api/media/live.d.ts
Labels: A-typings

#13835 修复Taro.showModal浏览器退回到上一页面不消失和遮罩层滚动透传问题
  packages/taro-h5/src/api/ui/interaction/modal.ts
  packages/taro-router/src/router/page.ts
  packages/taro-router/src/router/spa.ts
Labels: A-router, A-api, T-h5
