Repository NervJS/taro, pull requests merged in 2023-04, with the labels that each got.

#13550 fix(plugin): 修复禁用 ts 导致的插件导入报错 fix #13547
  packages/taro-components-advanced/rollup.config.js
  packages/taro-components-library-react/rollup.config.js
  packages/taro-components-library-vue2/rollup.config.js
  packages/taro-components-library-vue3/rollup.config.js
  packages/taro-components-react/rollup.config.js
  packages/taro-platform-h5/rollup.config.js
  packages/taro-plugin-html/rollup.config.js
  packages/taro-plugin-http/package.json
Labels: T-h5

#13597 fix(h5): 修补 tabbar 生命周期错误 fix #13581
  packages/taro-components/src/components/tabbar/tabbar.tsx
  packages/taro-h5/__tests__/utils.ts
Labels: A-components, T-h5

#13596 fix(h5): 修复 h5 依赖导出失败问题 fix #13586
  packages/taro-components-advanced/package.json
  packages/taro-platform-h5/rollup.config.js
  pnpm-lock.yaml
Labels: T-h5

#13496 fix(taro-components-rn): passthrough prop [scrollEventThrottle]
  packages/taro-components-rn/src/components/ScrollView/PropsType.tsx
  packages/taro-components-rn/src/components/ScrollView/index.tsx
Labels: T-rn

#13630 feat(router): 支持根据 html 模板自定义节点位置 fix #13382
  packages/taro-router/src/router/multi-page.ts
  packages/taro-router/src/router/page.ts
Labels: A-router, T-h5

#13643 fix(components): 修复 value 引用错误 fix #13641
  packages/taro-components/src/components/checkbox/checkbox-group.tsx
  packages/taro-components/src/components/form/form.tsx
  packages/taro-components/src/components/radio/radio-group.tsx
Labels: T-h5

#13660 chore(types): sync type form docs
  packages/taro-components/types/Input.d.ts
  packages/taro-components/types/Map.d.ts
  packages/taro-components/types/Picker.d.ts
  packages/taro/types/api/canvas/index.d.ts
  packages/taro/types/api/cloud/index.d.ts
  packages/taro/types/api/network/request.d.ts
  packages/taro/types/api/open-api/favorites.d.ts
  packages/taro/types/api/open-api/my-miniprogram.d.ts
  packages/taro/types/compile/config/project.d.ts
Labels: A-typings

#13659 feat(components): support textarea onConfirm #12911
  packages/taro-components/src/components/textarea/textarea.tsx
  packages/taro-components/types/Textarea.d.ts
Labels: T-h5

#13665 feat(h5): add cleanInterceptors
  packages/taro-h5/src/api/network/request/index.ts
  packages/taro/types/api/network/request.d.ts
Labels: A-typings, A-api, T-h5

#13680 revert(swiper): 回滚 change 事件设置 #12357
  packages/taro-components/src/components/swiper/swiper.tsx
Labels: A-components, T-h5

#13706 fix(types): 修复 taro getRandomValues 方法类型问题
  packages/taro/types/api/base/crypto.d.ts
Labels: A-typings

#13707 docs(miniprogram): getAppInfo 补充文档 types
  packages/taro/types/taro.extend.d.ts
Labels: A-docs

#13703 fix(taro-weapp): channels apis need promise
  packages/taro-mini-runner/src/__tests__/__snapshots__/babel.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/common-style.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/compiler-macros.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/config.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/css-modules.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/custom-tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/parse-html.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/prerender.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/qq.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/react.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/sass.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/subpackages.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/tabbar.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/ts.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/vue3.spec.ts.snap
  packages/taro-mini-runner/src/__tests__/__snapshots__/wx-hybrid.spec.ts.snap
  packages/taro-weapp/src/apis-list.ts
Labels: T-weapp

#13678 fix(alipay): support custom tabbar
  packages/taro-mini-runner/src/plugins/MiniPlugin.ts
  packages/taro-webpack5-runner/src/plugins/MiniPlugin.ts
Labels: T-alipay
