Repository NervJS/taro, pull requests merged in 2023-12, with the labels that each got.

#14946 fix(rn): adjusting tablet phone styles
  packages/taro-runtime-rn/package.json
  packages/taro-runtime-rn/src/compute.ts
  packages/taro-runtime-rn/src/scale2dp.tsx
  pnpm-lock.yaml
Labels: T-rn

#14964 fix: 优化loadFontFace成功回调信息以及setTabBarBadge上标显示
  packages/taro-h5/__tests__/ui/tab-bar.test.tsx
  packages/taro-h5/__tests__/utils.ts
  packages/taro-h5/src/api/ui/fonts.ts
  packages/taro-h5/src/api/ui/tab-bar.ts
Labels: T-h5

#14919 fix(components): 修复 state 更新导致的动画阻塞问题
  packages/taro-components/src/components/swiper/readme.md
  packages/taro-components/src/components/swiper/swiper-item.tsx
  packages/taro-components/src/components/swiper/swiper.tsx
  packages/taro-components/src/components/tabbar/readme.md
  packages/taro-components/types/SwiperItem.d.ts
Labels: A-components, T-h5

#14992 fix(h5): h5 端开启 enablePullDownRefresh 白屏问题修复
  packages/taro-components/__tests__/__snapshots__/pull-to-refresh.spec.tsx.snap
  packages/taro-components/src/components/pull-to-refresh/pull-to-refresh.tsx
  packages/taro-platform-h5/src/program.ts
  packages/taro-plugin-react/src/runtime/connect.ts
  packages/taro-plugin-vue2/src/runtime/connect.ts
  packages/taro-plugin-vue3/src/runtime/connect.ts
  packages/taro-service/src/platform-plugin-base/mini.ts
Labels: A-components, F-vue2, T-h5

#14958 fix: 修复window环境无法生成definition.json文件
  packages/taro-platform-h5/build/utils/ast.ts
Labels: A-components

#14940 Update taro.extend.d.ts
  packages/taro/types/api/taro.extend.d.ts
Labels: A-typings

#14960 feat: 增加navigationStyle配置处理逻辑
  packages/taro-router/src/router/multi-page.ts
  packages/taro-router/src/router/page.ts
  packages/taro-router/src/router/spa.ts
  packages/taro-router/src/style.ts
Labels: T-h5

#14963 fix: 组件Image兼容mode为空串和src无值的情况
  packages/taro-components/__tests__/__snapshots__/image.spec.tsx.snap
  packages/taro-components/package.json
  packages/taro-components/src/components/image/image.tsx
  pnpm-lock.yaml
Labels: A-components, T-h5

#15021 feat(h5): 移除 mobile-detect 依赖
  packages/stylelint-taro/.gitignore
  packages/taro-h5/package.json
  packages/taro-h5/src/api/base/system.ts
  packages/taro-h5/src/api/media/video/chooseMedia.ts
  packages/taro-router/src/utils/navigate.ts
  pnpm-lock.yaml
Labels: T-h5

#14793 Feature types canvas
  packages/taro-h5/src/api/canvas/CanvasContext.ts
  packages/taro/types/api/canvas/index.d.ts
Labels: A-typings
