Repository NervJS/taro, pull requests merged in 2024-01, with the labels that each got.

#15057 Feature type opanapi
  packages/taro-h5/src/api/qq/index.ts
  packages/taro/types/api/files/index.d.ts
  packages/taro/types/api/open-api/account.d.ts
  packages/taro/types/api/open-api/address.d.ts
  packages/taro/types/api/open-api/authorize.d.ts
  packages/taro/types/api/open-api/bookshelf.d.ts
  packages/taro/types/api/open-api/channels.d.ts
  packages/taro/types/api/open-api/device-voip.d.ts
  packages/taro/types/api/open-api/invoice.d.ts
  packages/taro/types/api/open-api/login.d.ts
  packages/taro/types/api/open-api/privacy.d.ts
  packages/taro/types/api/open-api/settings.d.ts
  packages/taro/types/api/open-api/sticker.d.ts
  packages/taro/types/api/open-api/subscribe-message.d.ts
  packages/taro/types/api/open-api/user-info.d.ts
  packages/taro/types/api/qq/index.d.ts
  packages/taro/types/api/swan/download-package.d.ts
  packages/taro/types/api/swan/index.d.ts
  packages/taro/types/api/swan/pay.d.ts
  packages/taro/types/api/ui/interaction.d.ts
  packages/taro/types/index.d.ts
  packages/taro/types/taro.api.d.ts
Labels: A-typings

#15080 feat(h5): 优化初始项目包体积抖动
  LICENSE
  package.json
  packages/babel-preset-taro/package.json
  packages/shared/src/runtime-hooks.ts
  packages/taro-alipay/package.json
  packages/taro-cli-convertor/package.json
  packages/taro-components-library-react/package.json
  packages/taro-components-library-react/rollup.config.js
  packages/taro-components-library-vue2/package.json
  packages/taro-components-library-vue2/rollup.config.js
  packages/taro-components-library-vue3/package.json
  packages/taro-components-library-vue3/rollup.config.js
  packages/taro-components/package.json
  packages/taro-platform-harmony-hybrid/package.json
  packages/taro-qq/package.json
  packages/taro-service/package.json
  packages/taro-swan/package.json
  packages/taro-tt/package.json
  packages/taro-weapp/package.json
  packages/taro-webpack5-prebundle/src/prebundle/bundle.ts
  packages/taro-webpack5-prebundle/src/prebundle/index.ts
  packages/taro-webpack5-prebundle/src/prebundle/scanImports.ts
  packages/taro-webpack5-prebundle/src/web.ts
  packages/taro/package.json
  pnpm-lock.yaml
Labels: T-h5

#15069 fix: 修复 `@tarojs/taro` 在 IDEA 中缺少 TS 类型提示
  packages/taro-cli/templates/default/package.json.tmpl
  packages/taro-cli/templates/default/tsconfig.json
  packages/taro-cli/templates/plugin-compile/tsconfig.json
Labels: A-typings

#15095 h5 平台 requestTask 增加 abort 接口
  packages/taro-h5/src/api/network/request/index.ts
Labels: T-h5

#15111 fix(taro-h5): 修复H5端timeout默认值不生效问题
  packages/taro-h5/src/api/network/request/index.ts
  packages/taro-rn/src/lib/request/index.ts
  packages/taro/types/api/network/request.d.ts
Labels: A-api, T-h5
