Repository NervJS/taro, pull requests merged in 2024-05, with the labels that each got.

#15577 【harmony-hybrid】解决打开第1个页面时在鸿蒙平台动画不能真正的停止的问题
  packages/taro-router/src/style.ts
Labels: T-harmony_hybrid

#15392 types: 修改request请求api的complete res参数类型，与success一致
  packages/taro/types/api/network/request.d.ts
Labels: A-typings

#15540 fix: 修改判断，考虑初始绑定的事件为空的情况
  packages/taro-components-library-react/src/react-component-lib/utils/attachProps.ts
Labels: A-components, T-h5

#15760 feat: 优化JSBridge中类实例方法过多问题
  examples/mini-program-example/src/pages/api/network/request/index.tsx
  packages/taro-platform-harmony-hybrid/src/api/apis/NativeApi.ts
  packages/taro-platform-harmony-hybrid/src/api/apis/interface/ClassInstanceManager.ts
  packages/taro-platform-harmony-hybrid/src/api/apis/interface/NativeAContextApi.ts
  packages/taro-platform-harmony-hybrid/src/api/apis/interface/NativeRequest.ts
  packages/taro-platform-harmony-hybrid/src/api/apis/interface/NativeUploadFile.ts
  packages/taro-platform-harmony-hybrid/src/api/apis/network/request/nativeRequest.ts
  packages/taro-platform-harmony-hybrid/src/api/apis/network/upload.ts
Labels: T-harmony_hybrid

#15582 fix: 修改Windows运行时sass1.37.5版本的sass uri must have scheme 'file:'的bug
  packages/taro-rn-style-transformer/src/transforms/sass.ts
Labels: T-rn
